get:
  description: Returns list of all trainings in current week
  tags:
    - Trainings
  operationId: trainingDetailsCurrentWeek
  responses:
    200:
      $ref: "../components/responses/TrainingDetailsCurrentWeekResponse.yaml"
