get:
  summary: Training summaries
  tags:
    - Trainings
  operationId: summariesPage
  parameters:
    - $ref: "../components/parameters/PageParam.yaml"
    - $ref: "../components/parameters/PageSizeParam.yaml"
  responses:
    200:
      $ref: "../components/responses/TrainingSummariesResponse.yaml"
