parameters:
  - name: id
    in: path
    required: true
    description: Id of a training
    schema:
      type: string
      format: uuid

get:
  summary: Get a training by id
  tags:
    - Trainings
  operationId: trainingById
  responses:
    200:
      $ref: "../components/responses/TrainingResponse.yaml"
    404:
      $ref: "../components/responses/errors/NotFoundResponse.yaml"

patch:
  summary: Edit training session
  tags:
    - Trainings
  operationId: editTrainingSession
  requestBody:
    $ref: "../components/requestBodies/EditSessionRequest.yaml"
  responses:
    200:
      $ref: "../components/responses/EditTrainingResponse.yaml"
    400:
      $ref: "../components/responses/errors/InvalidSessionResponse.yaml"
    404:
      $ref: "../components/responses/errors/NotFoundResponse.yaml"

delete:
  summary: Delete a training
  tags:
    - Trainings
  operationId: deleteTraining
  responses:
    204:
      description: Training was deleted
    404:
      $ref: "../components/responses/errors/NotFoundResponse.yaml"
