parameters:
  - $ref: "../components/parameters/TrainingIdParam.yaml"
  - $ref: "../components/parameters/SetIdParam.yaml"

patch:
  summary: Move set
  tags:
    - Trainings
  operationId: moveSet
  requestBody:
    $ref: "../components/requestBodies/MoveSetRequest.yaml"
  responses:
    200:
      $ref: "../components/responses/TrainingResponse.yaml"
    400:
      $ref: "../components/responses/errors/InvalidSetOrderResponse.yaml"
    404:
      $ref: "../components/responses/errors/NotFoundResponse.yaml"
