version: '3'
services:
  backend:
    build:
      context: ./backend/
    ports:
      - 42069:42069
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=42069

      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=swimlogs
      - DATABASE_PASSWORD=swimlogs
      - DATABASE_NAME=swimlogs
      - FE_ORIGIN=localhost:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=swimlogs
      - POSTGRES_PASSWORD=swimlogs
      - POSTGRES_DB=swimlogs
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'swimlogs']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db:
    driver: local
