version: '3'
services:
  backend:
    image: nesquiko/swimlogs-backend:1.0.0
    container_name: backend
    ports:
      - 42069:42069
    environment:
      - APP_HOST=0.0.0.0 # this is inside docker
      - APP_PORT=42069
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=swimlogs
      - DATABASE_PASSWORD=swimlogs
      - DATABASE_NAME=swimlogs
      - FE_ORIGIN=https://www.swimlogs.com
    restart: always
    healthcheck:
      test: 'wget --tries=1 --spider http://localhost:42069/monitoring/heartbeat || exit 1'
      interval: 5s
      timeout: 3s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=swimlogs
      - POSTGRES_PASSWORD=swimlogs
      - POSTGRES_DB=swimlogs
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'swimlogs']
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    image: nesquiko/swimlogs-frontend:1.0.0
    container_name: frontend
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --non-interactive --keep-until-expiring --webroot -w /var/www/certbot --email lukas.castven@gmail.com -d www.swimlogs.com --agree-tos

volumes:
  db:
