version: '3'

tasks:
  openapi-gen:
    dir: ./generator
    preconditions:
      - sh: command -v oapi-codegen
        msg: Oapi-codegen not installed! See ./doc/tech/setup.md to setup the project.
    cmds:
      - mkdir -p generated
      - oapi-codegen -config ./config/server.cfg.yaml ../doc/openapi/{{.SPEC}}
      - oapi-codegen -config ./config/models.cfg.yaml ../doc/openapi/{{.SPEC}}
    vars:
      SPEC:
        sh: ls -v ../doc/openapi | tail -n 1

  dev-db-start:
    preconditions:
      - sh: command -v docker
        msg: Docker isn't installed!
    cmds:
      - |
        docker run --name dev-psql \
        -e POSTGRES_USER=swimlogs \
        -e POSTGRES_PASSWORD=swimlogs \
        -e POSTGRES_DB=swimlogs \
        -p 2345:5432 \
        -d \
        postgres
