version: '3'

vars:
  DB_DOCKER_NAME: dev-psql

tasks:
  test:
    cmds:
      - go test ./...

  openapi-gen:
    deps: [check:oapi-codegen]
    dir: ./generator
    cmds:
      - mkdir -p oapiGen
      - oapi-codegen -config ./config/server.cfg.yaml ../doc/openapi/{{.SPEC}}
      - oapi-codegen -config ./config/models.cfg.yaml ../doc/openapi/{{.SPEC}}
    vars:
      SPEC:
        sh: ls -v ../doc/openapi | tail -n 1

  migration:new:
    deps: [check:migrate]
    preconditions:
      - sh: test -n "{{.CLI_ARGS}}"
        msg: No script name argument passed!
    cmds:
      - migrate create -seq -ext=.sql -dir=./migrations "{{.CLI_ARGS}}"

  dev-db-start:
    deps: [check:docker]
    preconditions:
      - sh: docker ps -a | grep "{{.DB_DOCKER_NAME}}"
        msg: Development DB isn't running! Run task dev-db-create first.
    cmds:
      - docker start "{{.DB_DOCKER_NAME}}"

  dev-db-create:
    deps: [check:docker]
    cmds:
      - |
        docker run --name {{.DB_DOCKER_NAME}} \
        -e POSTGRES_USER=swimlogs \
        -e POSTGRES_PASSWORD=swimlogs \
        -e POSTGRES_DB=swimlogs \
        -p 2345:5432 \
        -d \
        postgres

  check:migrate:
    preconditions:
      - sh: command -v migrate
        msg: Migrate isn't installed!

  check:docker:
    preconditions:
      - sh: command -v docker
        msg: Docker isn't installed!

  check:oapi-codegen:
    preconditions:
      - sh: command -v oapi-codegen
        msg: Oapi-codegen not installed! See ./doc/tech/setup.md to setup the project.
