type: object
properties:
  id:
    type: string
    format: uuid
  start:
    type: string
    format: date-time
    description: On what date and time does the training occur
  durationMin:
    type: integer
    description: How long does the session last, in minutes
    example: 60
  totalDistance:
    type: integer
    description: Sum of all distances in blocks in meters
    example: 2100
  sets:
    type: array
    items:
      $ref: "./TrainingSet.yaml"
required:
  - id
  - start
  - durationMin
  - totalDistance
  - sets
