allOf:
  - $ref: "./BaseTrainingSet.yaml"
  - type: object
    properties:
      id:
        type: string
        format: uuid
      setOrder:
        type: integer
        description: Indicates on what place in training this set is
      totalDistance:
        type: integer
        description: Total distance in this set
        example: 800
      style:
        $ref: "./Style.yaml"
      components:
        type: array
        items:
          $ref: "./SetComponent.yaml"
    required:
      - id
      - setOrder
      - type
      - repeat
      - distanceMeters
      - totalDistance
      - isMain
