allOf:
  - $ref: "./BaseTraining.yaml"
  - type: object
    properties:
      id:
        type: string
        format: uuid
      totalDistance:
        type: integer
      sets:
        type: array
        items:
          $ref: "./TrainingSet.yaml"
    required:
      - id
      - start
      - durationMinutes
      - sets
      - totalDistance
