// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.1-0.20240823215434-d232e9efa9f5 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EquipmentEnum.
const (
	Board     EquipmentEnum = "board"
	Fins      EquipmentEnum = "fins"
	Monofin   EquipmentEnum = "monofin"
	Paddles   EquipmentEnum = "paddles"
	Parachute EquipmentEnum = "parachute"
	PullBuoy  EquipmentEnum = "pull_buoy"
	Snorkel   EquipmentEnum = "snorkel"
)

// Defines values for GroupEnum.
const (
	Backstroke   GroupEnum = "backstroke"
	Bifi         GroupEnum = "bifi"
	Breaststroke GroupEnum = "breaststroke"
	Butterfly    GroupEnum = "butterfly"
	Freestyle    GroupEnum = "freestyle"
	Long         GroupEnum = "long"
	Middle       GroupEnum = "middle"
	Mono         GroupEnum = "mono"
	Sprint       GroupEnum = "sprint"
)

// Defines values for IntensityEnum.
const (
	En1 IntensityEnum = "en1"
	En2 IntensityEnum = "en2"
	En3 IntensityEnum = "en3"
	Rec IntensityEnum = "rec"
	Sp1 IntensityEnum = "sp1"
	Sp2 IntensityEnum = "sp2"
	Sp3 IntensityEnum = "sp3"
)

// Defines values for ProgressionEnum.
const (
	Asc  ProgressionEnum = "asc"
	Desc ProgressionEnum = "desc"
)

// Defines values for StartWithSecondsType.
const (
	Interval StartWithSecondsType = "interval"
	Pause    StartWithSecondsType = "pause"
)

// Defines values for StartWithoutSecondsType.
const (
	LastFinishes StartWithoutSecondsType = "last-finishes"
)

// Defines values for TypeEnum.
const (
	Compound TypeEnum = "compound"
	Normal   TypeEnum = "normal"
	Pyramid  TypeEnum = "pyramid"
	Super    TypeEnum = "super"
)

// BaseSetComponent defines model for BaseSetComponent.
type BaseSetComponent struct {
	ComponentOrders *[]int           `json:"componentOrders,omitempty"`
	Description     *string          `json:"description,omitempty"`
	DistanceMeters  *int             `json:"distanceMeters,omitempty"`
	Equipment       *[]EquipmentEnum `json:"equipment,omitempty"`
	Group           *GroupEnum       `json:"group,omitempty"`
	Intensity       *IntensityEnum   `json:"intensity,omitempty"`
	IterationOrder  *int             `json:"iterationOrder,omitempty"`
	Progression     *ProgressionEnum `json:"progression,omitempty"`
	Repeat          *int             `json:"repeat,omitempty"`
	Start           *Start           `json:"start,omitempty"`
}

// BaseTraining defines model for BaseTraining.
type BaseTraining struct {
	// DurationMinutes How long does the session last, in minutes
	DurationMinutes *int `json:"durationMinutes,omitempty"`

	// Start On what date and time does the training occur
	Start *time.Time `json:"start,omitempty"`
}

// BaseTrainingSet defines model for BaseTrainingSet.
type BaseTrainingSet struct {
	// Description Description of what to swim
	Description    *string          `json:"description,omitempty"`
	DistanceMeters *int             `json:"distanceMeters,omitempty"`
	Equipment      *[]EquipmentEnum `json:"equipment,omitempty"`
	Group          *GroupEnum       `json:"group,omitempty"`
	Intensity      *IntensityEnum   `json:"intensity,omitempty"`
	IsMain         *bool            `json:"isMain,omitempty"`
	Progression    *ProgressionEnum `json:"progression,omitempty"`

	// Repeat How many times to repeat this set
	Repeat *int      `json:"repeat,omitempty"`
	Start  *Start    `json:"start,omitempty"`
	Type   *TypeEnum `json:"type,omitempty"`
}

// EquipmentEnum defines model for EquipmentEnum.
type EquipmentEnum string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Code Machine understandable code of the error instance
	Code string `json:"code"`

	// Detail A human-readable explanation of the error
	Detail string `json:"detail"`

	// Status HTTP result status
	Status int `json:"status"`

	// Title Short human-readable summary of the error
	Title                string                 `json:"title"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// GroupEnum defines model for GroupEnum.
type GroupEnum string

// IntensityEnum defines model for IntensityEnum.
type IntensityEnum string

// NewSetComponent defines model for NewSetComponent.
type NewSetComponent struct {
	ComponentOrders []int               `json:"componentOrders"`
	Description     *string             `json:"description,omitempty"`
	DistanceMeters  int                 `json:"distanceMeters"`
	Equipment       *[]EquipmentEnum    `json:"equipment,omitempty"`
	Group           *GroupEnum          `json:"group,omitempty"`
	Intensity       *IntensityEnum      `json:"intensity,omitempty"`
	IterationOrder  *int                `json:"iterationOrder,omitempty"`
	Progression     *ProgressionEnum    `json:"progression,omitempty"`
	Repeat          int                 `json:"repeat"`
	Start           *Start              `json:"start,omitempty"`
	StyleId         *openapi_types.UUID `json:"styleId,omitempty"`
}

// NewTraining defines model for NewTraining.
type NewTraining struct {
	// DurationMinutes How long does the session last, in minutes
	DurationMinutes int              `json:"durationMinutes"`
	Sets            []NewTrainingSet `json:"sets"`

	// Start On what date and time does the training occur
	Start time.Time `json:"start"`
}

// NewTrainingSet defines model for NewTrainingSet.
type NewTrainingSet struct {
	Components *[]NewSetComponent `json:"components,omitempty"`

	// Description Description of what to swim
	Description    *string          `json:"description,omitempty"`
	DistanceMeters int              `json:"distanceMeters"`
	Equipment      *[]EquipmentEnum `json:"equipment,omitempty"`
	Group          *GroupEnum       `json:"group,omitempty"`
	Intensity      *IntensityEnum   `json:"intensity,omitempty"`
	IsMain         *bool            `json:"isMain,omitempty"`
	Progression    *ProgressionEnum `json:"progression,omitempty"`

	// Repeat How many times to repeat this set
	Repeat int `json:"repeat"`

	// SetOrder Indicates on what place in training this set is
	SetOrder int                 `json:"setOrder"`
	Start    *Start              `json:"start,omitempty"`
	StyleId  *openapi_types.UUID `json:"styleId,omitempty"`
	Type     TypeEnum            `json:"type"`
}

// Pagination Pagination metadata about paginated response
type Pagination struct {
	// Page Number of page returned
	Page int `json:"page"`

	// PageSize How many items are in page
	PageSize int `json:"pageSize"`

	// Total Total count of all items
	Total int `json:"total"`
}

// ProgressionEnum defines model for ProgressionEnum.
type ProgressionEnum string

// SetComponent defines model for SetComponent.
type SetComponent struct {
	ComponentOrders []int              `json:"componentOrders"`
	Description     *string            `json:"description,omitempty"`
	DistanceMeters  int                `json:"distanceMeters"`
	Equipment       *[]EquipmentEnum   `json:"equipment,omitempty"`
	Group           *GroupEnum         `json:"group,omitempty"`
	Id              openapi_types.UUID `json:"id"`
	Intensity       *IntensityEnum     `json:"intensity,omitempty"`
	IterationOrder  *int               `json:"iterationOrder,omitempty"`
	Progression     *ProgressionEnum   `json:"progression,omitempty"`
	Repeat          int                `json:"repeat"`
	Start           *Start             `json:"start,omitempty"`
	Style           *Style             `json:"style,omitempty"`
}

// Start defines model for Start.
type Start struct {
	union json.RawMessage
}

// StartWithSeconds defines model for StartWithSeconds.
type StartWithSeconds struct {
	Seconds int                  `json:"seconds"`
	Type    StartWithSecondsType `json:"type"`
}

// StartWithSecondsType defines model for StartWithSeconds.Type.
type StartWithSecondsType string

// StartWithoutSeconds defines model for StartWithoutSeconds.
type StartWithoutSeconds struct {
	Type StartWithoutSecondsType `json:"type"`
}

// StartWithoutSecondsType defines model for StartWithoutSeconds.Type.
type StartWithoutSecondsType string

// Style defines model for Style.
type Style struct {
	ExecriseDescription *string            `json:"execriseDescription,omitempty"`
	ExecriseName        *string            `json:"execriseName,omitempty"`
	Id                  openapi_types.UUID `json:"id"`
	Name                string             `json:"name"`
}

// Training defines model for Training.
type Training struct {
	// DurationMinutes How long does the session last, in minutes
	DurationMinutes int                `json:"durationMinutes"`
	Id              openapi_types.UUID `json:"id"`
	Sets            []TrainingSet      `json:"sets"`

	// Start On what date and time does the training occur
	Start         time.Time `json:"start"`
	TotalDistance int       `json:"totalDistance"`
}

// TrainingSet defines model for TrainingSet.
type TrainingSet struct {
	Components *[]SetComponent `json:"components,omitempty"`

	// Description Description of what to swim
	Description    *string            `json:"description,omitempty"`
	DistanceMeters int                `json:"distanceMeters"`
	Equipment      *[]EquipmentEnum   `json:"equipment,omitempty"`
	Group          *GroupEnum         `json:"group,omitempty"`
	Id             openapi_types.UUID `json:"id"`
	Intensity      *IntensityEnum     `json:"intensity,omitempty"`
	IsMain         bool               `json:"isMain"`
	Progression    *ProgressionEnum   `json:"progression,omitempty"`

	// Repeat How many times to repeat this set
	Repeat int `json:"repeat"`

	// SetOrder Indicates on what place in training this set is
	SetOrder int    `json:"setOrder"`
	Start    *Start `json:"start,omitempty"`
	Style    *Style `json:"style,omitempty"`

	// TotalDistance Total distance in this set
	TotalDistance int      `json:"totalDistance"`
	Type          TypeEnum `json:"type"`
}

// TrainingSummary defines model for TrainingSummary.
type TrainingSummary struct {
	// DurationMinutes How long does the session last, in minutes
	DurationMinutes int                `json:"durationMinutes"`
	Id              openapi_types.UUID `json:"id"`
	MainSets        *[]TrainingSet     `json:"mainSets,omitempty"`

	// Start On what date and time does the training occur
	Start time.Time `json:"start"`

	// TotalDistance Total distance in the training in meters
	TotalDistance int `json:"totalDistance"`
}

// TypeEnum defines model for TypeEnum.
type TypeEnum string

// FromParam defines model for FromParam.
type FromParam = time.Time

// IdParam defines model for IdParam.
type IdParam = openapi_types.UUID

// PageParam defines model for PageParam.
type PageParam = int

// PageSizeParam defines model for PageSizeParam.
type PageSizeParam = int

// UntilParam defines model for UntilParam.
type UntilParam = time.Time

// WithMainSetsParam defines model for WithMainSetsParam.
type WithMainSetsParam = bool

// CreateTrainingReponse defines model for CreateTrainingReponse.
type CreateTrainingReponse = Training

// EditSessionResponse defines model for EditSessionResponse.
type EditSessionResponse = TrainingSummary

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = ErrorDetail

// TrainingResponse defines model for TrainingResponse.
type TrainingResponse = Training

// TrainingSummariesResponse defines model for TrainingSummariesResponse.
type TrainingSummariesResponse struct {
	// Pagination Pagination metadata about paginated response
	Pagination Pagination        `json:"pagination"`
	Summaries  []TrainingSummary `json:"summaries"`
}

// CreateTrainingRequest defines model for CreateTrainingRequest.
type CreateTrainingRequest = NewTraining

// EditSessionRequest defines model for EditSessionRequest.
type EditSessionRequest = BaseTraining

// EditSetRequest defines model for EditSetRequest.
type EditSetRequest struct {
	// Description Description of what to swim
	Description    *string          `json:"description,omitempty"`
	DistanceMeters *int             `json:"distanceMeters,omitempty"`
	Equipment      *[]EquipmentEnum `json:"equipment,omitempty"`
	Group          *GroupEnum       `json:"group,omitempty"`
	Intensity      *IntensityEnum   `json:"intensity,omitempty"`
	IsMain         *bool            `json:"isMain,omitempty"`
	Progression    *ProgressionEnum `json:"progression,omitempty"`

	// Repeat How many times to repeat this set
	Repeat  *int                `json:"repeat,omitempty"`
	Start   *Start              `json:"start,omitempty"`
	StyleId *openapi_types.UUID `json:"styleId,omitempty"`
	Type    *TypeEnum           `json:"type,omitempty"`
}

// MoveSetRequest defines model for MoveSetRequest.
type MoveSetRequest struct {
	// NewSetOrder New setOrder of the set
	NewSetOrder int `json:"newSetOrder"`
}

// ReplaceSetComponentsRequest defines model for ReplaceSetComponentsRequest.
type ReplaceSetComponentsRequest struct {
	Components []NewSetComponent `json:"components"`
}

// EditSetJSONBody defines parameters for EditSet.
type EditSetJSONBody struct {
	// Description Description of what to swim
	Description    *string          `json:"description,omitempty"`
	DistanceMeters *int             `json:"distanceMeters,omitempty"`
	Equipment      *[]EquipmentEnum `json:"equipment,omitempty"`
	Group          *GroupEnum       `json:"group,omitempty"`
	Intensity      *IntensityEnum   `json:"intensity,omitempty"`
	IsMain         *bool            `json:"isMain,omitempty"`
	Progression    *ProgressionEnum `json:"progression,omitempty"`

	// Repeat How many times to repeat this set
	Repeat  *int                `json:"repeat,omitempty"`
	Start   *Start              `json:"start,omitempty"`
	StyleId *openapi_types.UUID `json:"styleId,omitempty"`
	Type    *TypeEnum           `json:"type,omitempty"`
}

// ReplaceSetComponentsJSONBody defines parameters for ReplaceSetComponents.
type ReplaceSetComponentsJSONBody struct {
	Components []NewSetComponent `json:"components"`
}

// MoveSetJSONBody defines parameters for MoveSet.
type MoveSetJSONBody struct {
	// NewSetOrder New setOrder of the set
	NewSetOrder int `json:"newSetOrder"`
}

// SummariesPageParams defines parameters for SummariesPage.
type SummariesPageParams struct {
	// Page Which page to return, starts at 0
	Page PageParam `form:"page" json:"page"`

	// PageSize How many resources to return
	PageSize PageSizeParam `form:"pageSize" json:"pageSize"`

	// From The beginning of the date time range.
	From *FromParam `form:"from,omitempty" json:"from,omitempty"`

	// Until The end of the date time range
	Until *UntilParam `form:"until,omitempty" json:"until,omitempty"`

	// WithMainSets If training summaries should contain main sets
	WithMainSets *WithMainSetsParam `form:"withMainSets,omitempty" json:"withMainSets,omitempty"`
}

// EditSetJSONRequestBody defines body for EditSet for application/json ContentType.
type EditSetJSONRequestBody EditSetJSONBody

// ReplaceSetComponentsJSONRequestBody defines body for ReplaceSetComponents for application/json ContentType.
type ReplaceSetComponentsJSONRequestBody ReplaceSetComponentsJSONBody

// MoveSetJSONRequestBody defines body for MoveSet for application/json ContentType.
type MoveSetJSONRequestBody MoveSetJSONBody

// CreateTrainingJSONRequestBody defines body for CreateTraining for application/json ContentType.
type CreateTrainingJSONRequestBody = NewTraining

// EditTrainingSessionJSONRequestBody defines body for EditTrainingSession for application/json ContentType.
type EditTrainingSessionJSONRequestBody = BaseTraining

// Getter for additional properties for ErrorDetail. Returns the specified
// element and whether it was found
func (a ErrorDetail) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ErrorDetail
func (a *ErrorDetail) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ErrorDetail to handle AdditionalProperties
func (a *ErrorDetail) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ErrorDetail to handle AdditionalProperties
func (a ErrorDetail) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	object["detail"], err = json.Marshal(a.Detail)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'detail': %w", err)
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsStartWithoutSeconds returns the union data inside the Start as a StartWithoutSeconds
func (t Start) AsStartWithoutSeconds() (StartWithoutSeconds, error) {
	var body StartWithoutSeconds
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStartWithoutSeconds overwrites any union data inside the Start as the provided StartWithoutSeconds
func (t *Start) FromStartWithoutSeconds(v StartWithoutSeconds) error {
	v.Type = "last-finishes"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStartWithoutSeconds performs a merge with any union data inside the Start, using the provided StartWithoutSeconds
func (t *Start) MergeStartWithoutSeconds(v StartWithoutSeconds) error {
	v.Type = "last-finishes"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStartWithSeconds returns the union data inside the Start as a StartWithSeconds
func (t Start) AsStartWithSeconds() (StartWithSeconds, error) {
	var body StartWithSeconds
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStartWithSeconds overwrites any union data inside the Start as the provided StartWithSeconds
func (t *Start) FromStartWithSeconds(v StartWithSeconds) error {
	v.Type = "interval"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStartWithSeconds performs a merge with any union data inside the Start, using the provided StartWithSeconds
func (t *Start) MergeStartWithSeconds(v StartWithSeconds) error {
	v.Type = "interval"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Start) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Start) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "interval":
		return t.AsStartWithSeconds()
	case "last-finishes":
		return t.AsStartWithoutSeconds()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Start) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Start) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete a set
	// (DELETE /sets/{id})
	DeleteSet(w http.ResponseWriter, r *http.Request, id IdParam)
	// Edit set
	// (PATCH /sets/{id})
	EditSet(w http.ResponseWriter, r *http.Request, id IdParam)
	// Replace set's components
	// (PUT /sets/{id})
	ReplaceSetComponents(w http.ResponseWriter, r *http.Request, id IdParam)
	// Move set up or down in training
	// (PATCH /sets/{id}/move)
	MoveSet(w http.ResponseWriter, r *http.Request, id IdParam)
	// Create new training
	// (POST /trainings)
	CreateTraining(w http.ResponseWriter, r *http.Request)
	// Training summaries
	// (GET /trainings/summaries)
	SummariesPage(w http.ResponseWriter, r *http.Request, params SummariesPageParams)
	// Delete a training
	// (DELETE /trainings/{id})
	DeleteTraining(w http.ResponseWriter, r *http.Request, id IdParam)
	// Get a training by id
	// (GET /trainings/{id})
	TrainingById(w http.ResponseWriter, r *http.Request, id IdParam)
	// Edit training session
	// (PATCH /trainings/{id})
	EditTrainingSession(w http.ResponseWriter, r *http.Request, id IdParam)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Delete a set
// (DELETE /sets/{id})
func (_ Unimplemented) DeleteSet(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Edit set
// (PATCH /sets/{id})
func (_ Unimplemented) EditSet(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Replace set's components
// (PUT /sets/{id})
func (_ Unimplemented) ReplaceSetComponents(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Move set up or down in training
// (PATCH /sets/{id}/move)
func (_ Unimplemented) MoveSet(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create new training
// (POST /trainings)
func (_ Unimplemented) CreateTraining(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Training summaries
// (GET /trainings/summaries)
func (_ Unimplemented) SummariesPage(w http.ResponseWriter, r *http.Request, params SummariesPageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a training
// (DELETE /trainings/{id})
func (_ Unimplemented) DeleteTraining(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a training by id
// (GET /trainings/{id})
func (_ Unimplemented) TrainingById(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Edit training session
// (PATCH /trainings/{id})
func (_ Unimplemented) EditTrainingSession(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteSet operation middleware
func (siw *ServerInterfaceWrapper) DeleteSet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSet(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// EditSet operation middleware
func (siw *ServerInterfaceWrapper) EditSet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EditSet(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceSetComponents operation middleware
func (siw *ServerInterfaceWrapper) ReplaceSetComponents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceSetComponents(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// MoveSet operation middleware
func (siw *ServerInterfaceWrapper) MoveSet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MoveSet(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTraining operation middleware
func (siw *ServerInterfaceWrapper) CreateTraining(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTraining(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// SummariesPage operation middleware
func (siw *ServerInterfaceWrapper) SummariesPage(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SummariesPageParams

	// ------------- Required query parameter "page" -------------

	if paramValue := r.URL.Query().Get("page"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Required query parameter "pageSize" -------------

	if paramValue := r.URL.Query().Get("pageSize"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "until" -------------

	err = runtime.BindQueryParameter("form", true, false, "until", r.URL.Query(), &params.Until)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "until", Err: err})
		return
	}

	// ------------- Optional query parameter "withMainSets" -------------

	err = runtime.BindQueryParameter("form", true, false, "withMainSets", r.URL.Query(), &params.WithMainSets)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "withMainSets", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SummariesPage(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTraining operation middleware
func (siw *ServerInterfaceWrapper) DeleteTraining(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTraining(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TrainingById operation middleware
func (siw *ServerInterfaceWrapper) TrainingById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TrainingById(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// EditTrainingSession operation middleware
func (siw *ServerInterfaceWrapper) EditTrainingSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EditTrainingSession(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/sets/{id}", wrapper.DeleteSet)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/sets/{id}", wrapper.EditSet)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/sets/{id}", wrapper.ReplaceSetComponents)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/sets/{id}/move", wrapper.MoveSet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trainings", wrapper.CreateTraining)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trainings/summaries", wrapper.SummariesPage)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trainings/{id}", wrapper.DeleteTraining)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trainings/{id}", wrapper.TrainingById)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/trainings/{id}", wrapper.EditTrainingSession)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaX4/buBH/KgRboC/K2pvkitZvl0tyNZBNFmcf8hAserQ0tnmRSB1JreMu/N2LIan/",
	"tCU7zrUH3MsmlijOj/N/hvNEY5nlUoAwms6eaM4Uy8CAsr/eKpnd4xP8kYCOFc8Nl4LO6HILZAUbLgQX",
	"GyLXxGyBJMwAMTwDopjYwA2NKMfFvxWg9jSigmVAZ3StZEYjquMtZAy3XkuVMUNnFDd4hhvQiJp9jou1",
	"UVxs6OEQ0XlyBMw8QQSMKNCyUDGUdHNmtjVZntCIKvit4AoSOjOqgCCIorAr+/Tv2QaOIPi45fGW5GwD",
	"xEiiwBRKREQbpowmzJDpEVbgFydRwReW5SnQ2TSiGRc8KzL7f4+OCwMbUBW8Bf/PMYj/kjuSMbGvuKRr",
	"qCfQ4Y7jEN4iRPbFQfyuifc2iPdnYXh6Qr1AJEcU6wjcAje8RLE+crO9Y1wswOhjKrYmRjFutV0XWcYU",
	"B030VhZpQmIpDOOCZPhHg9FHAO4adFo4PaSVlCkwQQ8ICjkO2rySCQdrjT8oYAaWHsVP7jW+QPIg7H9Z",
	"nqc8Zgh68qtG5E8NMn9VsKYz+pdJbfQT91ZP3sOu3NrRb5/fkyNrqUiMQJARrOJJT0MOEX2TcLMArbkU",
	"1wb7imkYixYS3gFLtEN1HLS5BDBL0w9rOvs0HvoCDD1ETzRXMgdlvJy12acwT8b5JP9Ern6F2NDDw2hm",
	"aDA35G3jUY21tDoNhhQayC/3Py/JBPV68sSTwy8hvt3JR7iQb+3TC9gtwHxQCai+Fb6HHaKybxsoacPx",
	"vPznoKOswX9qkXvosfM0MzP56LTJEC6IrEDVambNvMernyBPWYzs+qHi+dczrh3IuYFMj7D5Jgha6xNT",
	"iu17zGqQGMcre05N4AvXpmRVQ8/QHxIBOyIFBDhlqetcCh12gPbN1XzKKX+CeleJdcc00UUcg9brIk33",
	"zh9CQrs+T38bgAsbfvYhnMs6RDXwoYV7eEpJdXVgdtfXYBhPQ6Be218r1ANcSMyWGSLjuFCQkKRAV0a2",
	"TCSpzyQxj3PGcIhoLW39+4m7JOYUtBHlGoAWZRJwEbK26eZswwVzxE+jvq9XHiJaJSKjLb6nQwMWX1OI",
	"mijHWL+HCglJuTZtx1jtip95bAgdg2PLIx33ctZltw8+OgZ0D92B/tSNsxFNuDZMxHBX1UYVsRfT6XQg",
	"2Y0osjTP/IlGSepN+cUbUWQhyBsli3xolx9xUbkD4hGam/3QV/NyYfWlAWUlX8XlM3idK7lRPuMaUu96",
	"aUlaQQ7MtEh+N8xvW3kNUVvYRYEsKqKtBLOnhEnhuHHHRWH8o16tlUqxIYnEMstmKfZUJGXaRJguZP7b",
	"6ExNqk7WpvhBkB36VVspMZG4aqkiX5me9bs0GlsZnWQMpq993rQtKRQK7C90CBaxkUTveEajupKkbxWA",
	"TYP7oP60RY0lZKhqvJ6pHekcoJr4rgGuJGbLdTf/vrJxlt8PhLV9Du4UIZ1ti2/2RMH++4muubAGKIVc",
	"cywHtZDqM6Q0oivJVGKDXpKkPvwpFm8LgzqZF2n671Uh941IWCtoMx/CTCDBCksKlt43LMW1UbrBLYE+",
	"++9YvOUCSCEw4hkmErZKgeDisgZyiRUXzjCCRlPBaW/+PdkWGRPPFDC3LXzJU+bCfGv30KbaMFOE3N9y",
	"eU8U6CI1xK8JBmFu0sB5F1upTBeWSxn2A5A62YsjUOGMHIMrZjwEdKU20qaeNNzRSgHTRhslP9ufLP5c",
	"/yiMAbVO916p8BFfc0SQKy6snXDUJxpRDA9B7WkbfAOFghidpLi1f5/bvy/s3rf273P790Vw026ld1a7",
	"olMjflW/oike7296Hj3qZXkPgUaHPVQzRp/ffwkdBs6rn9utHHSDc/elb4D6X7dDebb1dlEvs4gcoMHz",
	"+1B8rRbUdXoJo5lhT3mk5TMXCZZRoIn0KY5tKmAKVSU1ZRwiXJ/TCoouV90Kb3RCi+0WYdHdtyq+YOGE",
	"DjgDwxJmGGErWRiSVyVV2RehUb+UDLjU90W2cs0pe0Xhmv6QNHOucOpeXgAczwmschCmrET8dUbrSiDg",
	"96VhgVC0xMckloWw1SJLU7d5a8MXgx09t3tUXq1URwh5+24S1PC2TMfU1YVBh/rNvCkfo41ec4dzKFzU",
	"ZZC/B/s637uoyhCOMsxQL6WvDPPce2QUkXpEWZ/I8T5ys11ALEWC1LE+erbmgust8mPgO1mY+tOcFRpG",
	"kzpUlrN/725n7CkPEZUCRogyhAGlOeqb6oOKlc2ns35Qql6cV+qUuXOp1I5FUS2Yh8EUCt9GFYKQEYU4",
	"0TtCF0lbzuNghIl7O2iTgy8QK67h9UBfp1znVMCy9x2Ijdm6mNVbP9I6xajtQnZpvwwd9OqZzlhHc05C",
	"1MmGulHeuubX3uE05HHMlVtEA6lRd9ewu/r/yZNOX7hEZ4jlagnTkbxoZHQJiDUU18s4Y3HUfYMqsv9j",
	"OnxZ5/ShTr28czqRgbWQVb2TAR3xvfFv3ParTv73YJI0Ug+ycpzgSib6O7YXL1KcBi1u82Mn6IqZz5+P",
	"1qOjfmXIoUS06jc1IprAI6dlAlUI2z3aK5Y5akXeumGuYoDtBa5lgOU5CJZzonOI+dpfJdl758WOZ+/k",
	"RpPv7+c3mDPxGPwFlB80uZsvyTv/NKKFwgxsa0yuZ5OJzEG4AaAbqTYT/7Ge3M2XjaYMbRKhEX0E5bqK",
	"9PZmejO1eZIDSGf0hX0U2Xkrq4D1sIA7VwrGwkNrsufAmou+ts8X1g+0LnqfT18G2kJg7NWr281eZ750",
	"60LqXu03ad95Hqprs32FwE1DoODZRqMorUE9HKLWONyRYFEvmZTzaYcHy4p42z+yHy+hzfGe/fEzNCaA",
	"Jp3JlEOPZ9NhXvRuUy0Tp2cz8Qqsx+McZXth+qwLTU1cwsdT0xd/dKb6syFf/6YbkxZ9Jh+ihpFOMvkI",
	"3fHPq+i7Hwu6RE6diaI/umjwOG6iKidSkUTuRDMlC0uofOsKKqkDZtEeirmE0eG5wj6/b4cZEJ7QuZDp",
	"Lfa5ne2wUIBly4pPHb5NWiMSGwgwsBrkuC8bRufYQD0TfKz47yyuJ3RHfFAPYI9Y3JinHbG6P/OKZny5",
	"ifXnYa4h9mV/ZGSM1MdlHi2jGUo/ls3xr2+SgwzodRRW33LJq/08odfzkV95qB/BNAduV3viypfgub5J",
	"llXXOc1Z3wsyrtYA80VRKDQU+D9OvAKj0EGrsp0G9ViKpnNRoWRCViz+DCIhblmv2tjtdjd6x7NUbvRN",
	"LLMJVgwoOk+uKllqsoeHw38DAAD//5m6/n6XMgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
