// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.1-0.20240823215434-d232e9efa9f5 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EquipmentEnum.
const (
	Board     EquipmentEnum = "board"
	Fins      EquipmentEnum = "fins"
	Monofin   EquipmentEnum = "monofin"
	Paddles   EquipmentEnum = "paddles"
	Parachute EquipmentEnum = "parachute"
	PullBuoy  EquipmentEnum = "pull_buoy"
	Snorkel   EquipmentEnum = "snorkel"
)

// Defines values for GroupEnum.
const (
	Backstroke   GroupEnum = "backstroke"
	Bifi         GroupEnum = "bifi"
	Breaststroke GroupEnum = "breaststroke"
	Butterfly    GroupEnum = "butterfly"
	Freestyle    GroupEnum = "freestyle"
	Long         GroupEnum = "long"
	Middle       GroupEnum = "middle"
	Mono         GroupEnum = "mono"
	Sprint       GroupEnum = "sprint"
)

// Defines values for IntensityEnum.
const (
	En1 IntensityEnum = "en1"
	En2 IntensityEnum = "en2"
	En3 IntensityEnum = "en3"
	Rec IntensityEnum = "rec"
	Sp1 IntensityEnum = "sp1"
	Sp2 IntensityEnum = "sp2"
	Sp3 IntensityEnum = "sp3"
)

// Defines values for IntervalType.
const (
	IntervalTypeInterval IntervalType = "interval"
)

// Defines values for LastFinishesType.
const (
	LastFinishesTypeLastFinishes LastFinishesType = "last-finishes"
)

// Defines values for PauseType.
const (
	PauseTypePause PauseType = "pause"
)

// Defines values for ProgressionEnum.
const (
	Asc  ProgressionEnum = "asc"
	Desc ProgressionEnum = "desc"
)

// Defines values for TypeEnum.
const (
	Compound TypeEnum = "compound"
	Normal   TypeEnum = "normal"
	Pyramid  TypeEnum = "pyramid"
	Super    TypeEnum = "super"
)

// BaseSetComponent defines model for BaseSetComponent.
type BaseSetComponent struct {
	ComponentOrders *[]int                             `json:"componentOrders,omitempty"`
	Description     *string                            `json:"description,omitempty"`
	DistanceMeters  *int                               `json:"distanceMeters,omitempty"`
	Equipment       *[]EquipmentEnum                   `json:"equipment,omitempty"`
	Group           nullable.Nullable[GroupEnum]       `json:"group,omitempty"`
	Intensity       nullable.Nullable[IntensityEnum]   `json:"intensity,omitempty"`
	IterationOrder  *int                               `json:"iterationOrder,omitempty"`
	Progression     nullable.Nullable[ProgressionEnum] `json:"progression,omitempty"`
	Repeat          *int                               `json:"repeat,omitempty"`
	Start           *Start                             `json:"start,omitempty"`
}

// BaseTraining defines model for BaseTraining.
type BaseTraining struct {
	// DurationMinutes How long does the session last, in minutes
	DurationMinutes *int `json:"durationMinutes,omitempty"`

	// Start On what date and time does the training occur
	Start *time.Time `json:"start,omitempty"`
}

// BaseTrainingSet defines model for BaseTrainingSet.
type BaseTrainingSet struct {
	// Description Description of what to swim
	Description    *string                            `json:"description,omitempty"`
	DistanceMeters *int                               `json:"distanceMeters,omitempty"`
	Equipment      *[]EquipmentEnum                   `json:"equipment,omitempty"`
	Group          nullable.Nullable[GroupEnum]       `json:"group,omitempty"`
	Intensity      nullable.Nullable[IntensityEnum]   `json:"intensity,omitempty"`
	IsMain         *bool                              `json:"isMain,omitempty"`
	Progression    nullable.Nullable[ProgressionEnum] `json:"progression,omitempty"`

	// Repeat How many times to repeat this set
	Repeat *int      `json:"repeat,omitempty"`
	Start  *Start    `json:"start,omitempty"`
	Type   *TypeEnum `json:"type,omitempty"`
}

// EquipmentEnum defines model for EquipmentEnum.
type EquipmentEnum string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Code Machine understandable code of the error instance
	Code string `json:"code"`

	// Detail A human-readable explanation of the error
	Detail string `json:"detail"`

	// Status HTTP result status
	Status int `json:"status"`

	// Title Short human-readable summary of the error
	Title                string                 `json:"title"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// GroupEnum defines model for GroupEnum.
type GroupEnum string

// IntensityEnum defines model for IntensityEnum.
type IntensityEnum string

// Interval defines model for Interval.
type Interval struct {
	Seconds int          `json:"seconds"`
	Type    IntervalType `json:"type"`
}

// IntervalType defines model for Interval.Type.
type IntervalType string

// LastFinishes defines model for LastFinishes.
type LastFinishes struct {
	Type LastFinishesType `json:"type"`
}

// LastFinishesType defines model for LastFinishes.Type.
type LastFinishesType string

// NewSetComponent defines model for NewSetComponent.
type NewSetComponent struct {
	ComponentOrders []int                              `json:"componentOrders"`
	Description     *string                            `json:"description,omitempty"`
	DistanceMeters  int                                `json:"distanceMeters"`
	Equipment       *[]EquipmentEnum                   `json:"equipment,omitempty"`
	Group           nullable.Nullable[GroupEnum]       `json:"group,omitempty"`
	Intensity       nullable.Nullable[IntensityEnum]   `json:"intensity,omitempty"`
	IterationOrder  *int                               `json:"iterationOrder,omitempty"`
	Progression     nullable.Nullable[ProgressionEnum] `json:"progression,omitempty"`
	Repeat          int                                `json:"repeat"`
	Start           *Start                             `json:"start,omitempty"`
	StyleId         *openapi_types.UUID                `json:"styleId,omitempty"`
}

// NewTraining defines model for NewTraining.
type NewTraining struct {
	// DurationMinutes How long does the session last, in minutes
	DurationMinutes int              `json:"durationMinutes"`
	Sets            []NewTrainingSet `json:"sets"`

	// Start On what date and time does the training occur
	Start time.Time `json:"start"`
}

// NewTrainingSet defines model for NewTrainingSet.
type NewTrainingSet struct {
	Components *[]NewSetComponent `json:"components,omitempty"`

	// Description Description of what to swim
	Description    *string                            `json:"description,omitempty"`
	DistanceMeters int                                `json:"distanceMeters"`
	Equipment      *[]EquipmentEnum                   `json:"equipment,omitempty"`
	Group          nullable.Nullable[GroupEnum]       `json:"group,omitempty"`
	Intensity      nullable.Nullable[IntensityEnum]   `json:"intensity,omitempty"`
	IsMain         *bool                              `json:"isMain,omitempty"`
	Progression    nullable.Nullable[ProgressionEnum] `json:"progression,omitempty"`

	// Repeat How many times to repeat this set
	Repeat int `json:"repeat"`

	// SetOrder Indicates on what place in training this set is
	SetOrder int                 `json:"setOrder"`
	Start    *Start              `json:"start,omitempty"`
	StyleId  *openapi_types.UUID `json:"styleId,omitempty"`
	Type     TypeEnum            `json:"type"`
}

// Pagination Pagination metadata about paginated response
type Pagination struct {
	// Page Number of page returned
	Page int `json:"page"`

	// PageSize How many items are in page
	PageSize int `json:"pageSize"`

	// Total Total count of all items
	Total int `json:"total"`
}

// Pause defines model for Pause.
type Pause struct {
	Seconds int       `json:"seconds"`
	Type    PauseType `json:"type"`
}

// PauseType defines model for Pause.Type.
type PauseType string

// ProgressionEnum defines model for ProgressionEnum.
type ProgressionEnum string

// SetComponent defines model for SetComponent.
type SetComponent struct {
	ComponentOrders []int                              `json:"componentOrders"`
	Description     *string                            `json:"description,omitempty"`
	DistanceMeters  int                                `json:"distanceMeters"`
	Equipment       *[]EquipmentEnum                   `json:"equipment,omitempty"`
	Group           nullable.Nullable[GroupEnum]       `json:"group,omitempty"`
	Id              openapi_types.UUID                 `json:"id"`
	Intensity       nullable.Nullable[IntensityEnum]   `json:"intensity,omitempty"`
	IterationOrder  *int                               `json:"iterationOrder,omitempty"`
	Progression     nullable.Nullable[ProgressionEnum] `json:"progression,omitempty"`
	Repeat          int                                `json:"repeat"`
	Start           *Start                             `json:"start,omitempty"`
	Style           *Style                             `json:"style,omitempty"`
}

// Start defines model for Start.
type Start struct {
	union json.RawMessage
}

// Style defines model for Style.
type Style struct {
	ExecriseDescription *string            `json:"execriseDescription,omitempty"`
	ExecriseName        *string            `json:"execriseName,omitempty"`
	Id                  openapi_types.UUID `json:"id"`
	Name                string             `json:"name"`
}

// Training defines model for Training.
type Training struct {
	// DurationMinutes How long does the session last, in minutes
	DurationMinutes int                `json:"durationMinutes"`
	Id              openapi_types.UUID `json:"id"`
	Sets            []TrainingSet      `json:"sets"`

	// Start On what date and time does the training occur
	Start         time.Time `json:"start"`
	TotalDistance int       `json:"totalDistance"`
}

// TrainingSet defines model for TrainingSet.
type TrainingSet struct {
	Components *[]SetComponent `json:"components,omitempty"`

	// Description Description of what to swim
	Description    *string                            `json:"description,omitempty"`
	DistanceMeters int                                `json:"distanceMeters"`
	Equipment      *[]EquipmentEnum                   `json:"equipment,omitempty"`
	Group          nullable.Nullable[GroupEnum]       `json:"group,omitempty"`
	Id             openapi_types.UUID                 `json:"id"`
	Intensity      nullable.Nullable[IntensityEnum]   `json:"intensity,omitempty"`
	IsMain         bool                               `json:"isMain"`
	Progression    nullable.Nullable[ProgressionEnum] `json:"progression,omitempty"`

	// Repeat How many times to repeat this set
	Repeat int `json:"repeat"`

	// SetOrder Indicates on what place in training this set is
	SetOrder int    `json:"setOrder"`
	Start    *Start `json:"start,omitempty"`
	Style    *Style `json:"style,omitempty"`

	// TotalDistance Total distance in this set
	TotalDistance int      `json:"totalDistance"`
	Type          TypeEnum `json:"type"`
}

// TrainingSummary defines model for TrainingSummary.
type TrainingSummary struct {
	// DurationMinutes How long does the session last, in minutes
	DurationMinutes int                `json:"durationMinutes"`
	Id              openapi_types.UUID `json:"id"`
	MainSets        *[]TrainingSet     `json:"mainSets,omitempty"`

	// Start On what date and time does the training occur
	Start time.Time `json:"start"`

	// TotalDistance Total distance in the training in meters
	TotalDistance int `json:"totalDistance"`
}

// TypeEnum defines model for TypeEnum.
type TypeEnum string

// FromParam defines model for FromParam.
type FromParam = time.Time

// IdParam defines model for IdParam.
type IdParam = openapi_types.UUID

// PageParam defines model for PageParam.
type PageParam = int

// PageSizeParam defines model for PageSizeParam.
type PageSizeParam = int

// UntilParam defines model for UntilParam.
type UntilParam = time.Time

// WithMainSetsParam defines model for WithMainSetsParam.
type WithMainSetsParam = bool

// CreateTrainingReponse defines model for CreateTrainingReponse.
type CreateTrainingReponse = Training

// EditSessionResponse defines model for EditSessionResponse.
type EditSessionResponse = TrainingSummary

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = ErrorDetail

// TrainingResponse defines model for TrainingResponse.
type TrainingResponse = Training

// TrainingSummariesResponse defines model for TrainingSummariesResponse.
type TrainingSummariesResponse struct {
	// Pagination Pagination metadata about paginated response
	Pagination Pagination        `json:"pagination"`
	Summaries  []TrainingSummary `json:"summaries"`
}

// CreateTrainingRequest defines model for CreateTrainingRequest.
type CreateTrainingRequest = NewTraining

// EditSessionRequest defines model for EditSessionRequest.
type EditSessionRequest = BaseTraining

// EditSetRequest defines model for EditSetRequest.
type EditSetRequest struct {
	Description    nullable.Nullable[string]          `json:"description,omitempty"`
	DistanceMeters *int                               `json:"distanceMeters,omitempty"`
	Equipment      *[]EquipmentEnum                   `json:"equipment,omitempty"`
	Group          nullable.Nullable[GroupEnum]       `json:"group,omitempty"`
	Intensity      nullable.Nullable[IntensityEnum]   `json:"intensity,omitempty"`
	IsMain         *bool                              `json:"isMain,omitempty"`
	Progression    nullable.Nullable[ProgressionEnum] `json:"progression,omitempty"`

	// Repeat How many times to repeat this set
	Repeat  *int                                  `json:"repeat,omitempty"`
	Start   nullable.Nullable[Start]              `json:"start,omitempty"`
	StyleId nullable.Nullable[openapi_types.UUID] `json:"styleId,omitempty"`
	Type    *TypeEnum                             `json:"type,omitempty"`
}

// MoveSetRequest defines model for MoveSetRequest.
type MoveSetRequest struct {
	// NewSetOrder New setOrder of the set
	NewSetOrder int `json:"newSetOrder"`
}

// ReplaceSetComponentsRequest defines model for ReplaceSetComponentsRequest.
type ReplaceSetComponentsRequest struct {
	Components []NewSetComponent `json:"components"`
}

// EditSetJSONBody defines parameters for EditSet.
type EditSetJSONBody struct {
	Description    nullable.Nullable[string]          `json:"description,omitempty"`
	DistanceMeters *int                               `json:"distanceMeters,omitempty"`
	Equipment      *[]EquipmentEnum                   `json:"equipment,omitempty"`
	Group          nullable.Nullable[GroupEnum]       `json:"group,omitempty"`
	Intensity      nullable.Nullable[IntensityEnum]   `json:"intensity,omitempty"`
	IsMain         *bool                              `json:"isMain,omitempty"`
	Progression    nullable.Nullable[ProgressionEnum] `json:"progression,omitempty"`

	// Repeat How many times to repeat this set
	Repeat  *int                                  `json:"repeat,omitempty"`
	Start   nullable.Nullable[Start]              `json:"start,omitempty"`
	StyleId nullable.Nullable[openapi_types.UUID] `json:"styleId,omitempty"`
	Type    *TypeEnum                             `json:"type,omitempty"`
}

// ReplaceSetComponentsJSONBody defines parameters for ReplaceSetComponents.
type ReplaceSetComponentsJSONBody struct {
	Components []NewSetComponent `json:"components"`
}

// MoveSetJSONBody defines parameters for MoveSet.
type MoveSetJSONBody struct {
	// NewSetOrder New setOrder of the set
	NewSetOrder int `json:"newSetOrder"`
}

// SummariesPageParams defines parameters for SummariesPage.
type SummariesPageParams struct {
	// Page Which page to return, starts at 0
	Page PageParam `form:"page" json:"page"`

	// PageSize How many resources to return
	PageSize PageSizeParam `form:"pageSize" json:"pageSize"`

	// From The beginning of the date time range.
	From *FromParam `form:"from,omitempty" json:"from,omitempty"`

	// Until The end of the date time range
	Until *UntilParam `form:"until,omitempty" json:"until,omitempty"`

	// WithMainSets If training summaries should contain main sets
	WithMainSets *WithMainSetsParam `form:"withMainSets,omitempty" json:"withMainSets,omitempty"`
}

// EditSetJSONRequestBody defines body for EditSet for application/json ContentType.
type EditSetJSONRequestBody EditSetJSONBody

// ReplaceSetComponentsJSONRequestBody defines body for ReplaceSetComponents for application/json ContentType.
type ReplaceSetComponentsJSONRequestBody ReplaceSetComponentsJSONBody

// MoveSetJSONRequestBody defines body for MoveSet for application/json ContentType.
type MoveSetJSONRequestBody MoveSetJSONBody

// CreateTrainingJSONRequestBody defines body for CreateTraining for application/json ContentType.
type CreateTrainingJSONRequestBody = NewTraining

// EditTrainingSessionJSONRequestBody defines body for EditTrainingSession for application/json ContentType.
type EditTrainingSessionJSONRequestBody = BaseTraining

// Getter for additional properties for ErrorDetail. Returns the specified
// element and whether it was found
func (a ErrorDetail) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ErrorDetail
func (a *ErrorDetail) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ErrorDetail to handle AdditionalProperties
func (a *ErrorDetail) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ErrorDetail to handle AdditionalProperties
func (a ErrorDetail) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	object["detail"], err = json.Marshal(a.Detail)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'detail': %w", err)
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsLastFinishes returns the union data inside the Start as a LastFinishes
func (t Start) AsLastFinishes() (LastFinishes, error) {
	var body LastFinishes
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLastFinishes overwrites any union data inside the Start as the provided LastFinishes
func (t *Start) FromLastFinishes(v LastFinishes) error {
	v.Type = "last-finishes"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLastFinishes performs a merge with any union data inside the Start, using the provided LastFinishes
func (t *Start) MergeLastFinishes(v LastFinishes) error {
	v.Type = "last-finishes"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPause returns the union data inside the Start as a Pause
func (t Start) AsPause() (Pause, error) {
	var body Pause
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPause overwrites any union data inside the Start as the provided Pause
func (t *Start) FromPause(v Pause) error {
	v.Type = "pause"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePause performs a merge with any union data inside the Start, using the provided Pause
func (t *Start) MergePause(v Pause) error {
	v.Type = "pause"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInterval returns the union data inside the Start as a Interval
func (t Start) AsInterval() (Interval, error) {
	var body Interval
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInterval overwrites any union data inside the Start as the provided Interval
func (t *Start) FromInterval(v Interval) error {
	v.Type = "interval"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInterval performs a merge with any union data inside the Start, using the provided Interval
func (t *Start) MergeInterval(v Interval) error {
	v.Type = "interval"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Start) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Start) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "interval":
		return t.AsInterval()
	case "last-finishes":
		return t.AsLastFinishes()
	case "pause":
		return t.AsPause()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Start) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Start) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete a set
	// (DELETE /sets/{id})
	DeleteSet(w http.ResponseWriter, r *http.Request, id IdParam)
	// Edit set
	// (PATCH /sets/{id})
	EditSet(w http.ResponseWriter, r *http.Request, id IdParam)
	// Replace set's components
	// (PUT /sets/{id})
	ReplaceSetComponents(w http.ResponseWriter, r *http.Request, id IdParam)
	// Move set up or down in training
	// (PATCH /sets/{id}/move)
	MoveSet(w http.ResponseWriter, r *http.Request, id IdParam)
	// Create new training
	// (POST /trainings)
	CreateTraining(w http.ResponseWriter, r *http.Request)
	// Training summaries
	// (GET /trainings/summaries)
	SummariesPage(w http.ResponseWriter, r *http.Request, params SummariesPageParams)
	// Delete a training
	// (DELETE /trainings/{id})
	DeleteTraining(w http.ResponseWriter, r *http.Request, id IdParam)
	// Get a training by id
	// (GET /trainings/{id})
	TrainingById(w http.ResponseWriter, r *http.Request, id IdParam)
	// Edit training session
	// (PATCH /trainings/{id})
	EditTrainingSession(w http.ResponseWriter, r *http.Request, id IdParam)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Delete a set
// (DELETE /sets/{id})
func (_ Unimplemented) DeleteSet(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Edit set
// (PATCH /sets/{id})
func (_ Unimplemented) EditSet(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Replace set's components
// (PUT /sets/{id})
func (_ Unimplemented) ReplaceSetComponents(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Move set up or down in training
// (PATCH /sets/{id}/move)
func (_ Unimplemented) MoveSet(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create new training
// (POST /trainings)
func (_ Unimplemented) CreateTraining(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Training summaries
// (GET /trainings/summaries)
func (_ Unimplemented) SummariesPage(w http.ResponseWriter, r *http.Request, params SummariesPageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a training
// (DELETE /trainings/{id})
func (_ Unimplemented) DeleteTraining(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a training by id
// (GET /trainings/{id})
func (_ Unimplemented) TrainingById(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Edit training session
// (PATCH /trainings/{id})
func (_ Unimplemented) EditTrainingSession(w http.ResponseWriter, r *http.Request, id IdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteSet operation middleware
func (siw *ServerInterfaceWrapper) DeleteSet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSet(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// EditSet operation middleware
func (siw *ServerInterfaceWrapper) EditSet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EditSet(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceSetComponents operation middleware
func (siw *ServerInterfaceWrapper) ReplaceSetComponents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceSetComponents(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// MoveSet operation middleware
func (siw *ServerInterfaceWrapper) MoveSet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MoveSet(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTraining operation middleware
func (siw *ServerInterfaceWrapper) CreateTraining(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTraining(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// SummariesPage operation middleware
func (siw *ServerInterfaceWrapper) SummariesPage(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SummariesPageParams

	// ------------- Required query parameter "page" -------------

	if paramValue := r.URL.Query().Get("page"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Required query parameter "pageSize" -------------

	if paramValue := r.URL.Query().Get("pageSize"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "until" -------------

	err = runtime.BindQueryParameter("form", true, false, "until", r.URL.Query(), &params.Until)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "until", Err: err})
		return
	}

	// ------------- Optional query parameter "withMainSets" -------------

	err = runtime.BindQueryParameter("form", true, false, "withMainSets", r.URL.Query(), &params.WithMainSets)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "withMainSets", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SummariesPage(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTraining operation middleware
func (siw *ServerInterfaceWrapper) DeleteTraining(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTraining(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TrainingById operation middleware
func (siw *ServerInterfaceWrapper) TrainingById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TrainingById(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// EditTrainingSession operation middleware
func (siw *ServerInterfaceWrapper) EditTrainingSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EditTrainingSession(w, r, id)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/sets/{id}", wrapper.DeleteSet)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/sets/{id}", wrapper.EditSet)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/sets/{id}", wrapper.ReplaceSetComponents)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/sets/{id}/move", wrapper.MoveSet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trainings", wrapper.CreateTraining)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trainings/summaries", wrapper.SummariesPage)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trainings/{id}", wrapper.DeleteTraining)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trainings/{id}", wrapper.TrainingById)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/trainings/{id}", wrapper.EditTrainingSession)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa34/bNvL/Vwh+v8C9KGtvkh7u/NY0SW+BbLKoXfQhWFxpaWyzkUiVpNbxLfy/H4ak",
	"flOW1vH2rsC9bCKL4nxmOL85jzSWWS4FCKPp4pHmTLEMDCj79F7J7A5/wYcEdKx4brgUdEFXOyBr2HIh",
	"uNgSuSFmByRhBojhGRDFxBauaEQ5Lv69AHWgERUsA7qgGyUzGlEd7yBjuPVGqowZuqC4wQvcgEbUHHJc",
	"rI3iYkuPx4jeJANgbhJEwIgCLQsVQ0k3Z2ZXk+UJjaiC3wuuIKELowoIgigKu7JP/45tYQDBLzse70jO",
	"tkCMJApMoUREtGHKaMIMmQ+IAr84iQq+sixPgS7mEc244FmR2f97dFwY2IKq4C35v4Yg/kPuScbEoZKS",
	"rqGeQIc7TkN4jRDZVwfxuybe6yDen4Xh6Qn1ApEMKNYA3AI3PEexfuFmd8u4WILRQyq2IUYxbrVdF1nG",
	"FAdN9E4WaUJiKQzjgmT4R4PRAwD3DTotnB7SWsoUmKBHBIUSB23eyISDtcYfFDADK4/iJ/caXyB5EPa/",
	"LM9THjMEPftNI/LHBpn/V7ChC/p/s9roZ+6tnn2Efbm1o9/m35MjG6lIjEBQEKySSU9DjhF9l3CzBK25",
	"FJcG+4ZpmIoWEt4BS7RDNQzanAOYpemnDV18ng59CYYeo0eaK5mDMv6cW6w8UlGkKVujgTnL66hvRJGF",
	"PPMQuYFMj4nvXfnFO1FkuIXfkynFDvhsHdd0npZ2+fE+6oC1Ox1SuElCDnaEsRqWXP8GMe4/+aQ1mCvy",
	"vvFTDbp0KRoMKTSQX+9+XpEZGu3skSfHX0NKcSsf4EylaB+tgP0SzCeVgOq7mI+wR1T2bQMlbXjV138f",
	"jQI1+M8tcvc9cZ4WZiYfnKkYwgWRFajahqwP68nqJ8hTFqO4fqhk/u2Ca2cpk5T8o2W+AtFX846wGiSm",
	"ycryqQl85dqUomroGTp7ImBPpICApCx1nUuhw97dvrmYwzzlLFHvqmPdM010Eceg9aZI04Nz9pDQrkPX",
	"zwNwaWPrIYRzVcffBj60cA9PKakuDszu+hYM42kI1Fv7tEY9wIXE7JghMo4LBQlJCnRlZMdEkvo0GZNU",
	"ZwzHiNanrf+44y6JOQVthPAGoGWZ4ZyFrG26Odtywcpodgr1Xb0SI0eJYbLF93RoxOJrClET5RTr91Ah",
	"ISnXpu0Yq13xM48NoWPkb3mkYS9nXXab8ckxoB/NOwlFL4FIuDZMxHBbFX4VsVfz+Xwkk3+WBGSrZJGP",
	"7fIjLip3QDxCc3MY++qmXFh9aUDZk6/i8hNknSu5VT6dHFPvemlJWkEOzLRIfjcu7yo7m5CT9bOoiLay",
	"554SJoWTxi0XhQlkpLaQTKXYkkRiDWmzFMsVSZk2EaYLmf82eqImVZy1KX4SZI9+1ZaBTCSuFKzIV6Zn",
	"/S6NppZ9JwWDufliJDUPhQL7hA7BIjaS6D3PaFSXyfS9ArBpMY3+Z4tdW9RYH4dK4suZ2kBbBNXEt0Rw",
	"JTE7rrv594WNs/x+JKwdcnBchHS2fXyLRwr23890w4U1QCnkhmOtq4VUXyClEV1LphIb9JIk9eFPsXhX",
	"GNTJvEjTf64LeWhEwlpBm/kQZgIJVlhSsPSuYSmuoOsGtwT64r9l8Y4LIIXAiGeYSLAkJLi4rIFcYsWF",
	"M4yg0VRw2pt/T3ZFxsQLBcxtC1/zlLkw39o9tKk2zBQh97da3REFukgN8WuCQZibNMDvcieV6cJyKcNh",
	"BFIne3EEKpyRE3AljPuArtRG2tSThjtaK2DaaKPkF/vI4i/1Q2EMqE168EqFP/ENRwS54sLaCUd9ohHF",
	"8EDvo/HeRdsBNFApiNFpimv796X9+8rSurZ/X9q/ryYTUQ8s7ftzDbEUyRlutrTbEi4vSdyPHhu+jSrK",
	"oWP6wLR5zwXXO59BtzB3SWPQfbEpl0+jH6LarZef1NHqVNo9OQ93gU6j9V67FxejXq58H2gXWaaamc7T",
	"W3QhZuBpXYh2tw8V7cZ96Xvk/ul6rFqxMSPq5WeRAzTKv09oLtWlvExHZrIwLJcDjbMbkWAxCppInyja",
	"1gwmolVqWEZzwvVTGmrR+apb4Y1OaPGANd6765xG3RwsPzGMZWBYwgwjbC0LQ/KqMC27SzTqF+SBwPSx",
	"yNauxWdvsdy9ECTNzDVcAJV3RMOZlVUOwpQ9EX/j1bo1CvhXaVggoK/wZxLLQtiam6Wp27y14avRvqjb",
	"PSpv3yoWQm7xjhWu/fFMkSO3+18ibHST3gYRpmPq+gCTAuazxQE+xY68zY3n0LioKyd/yfttUWNZlaEc",
	"tS9Di5K+M5DnPpZUIf9EbWPfR50QPbC+FfUjrxeDnTJ8eaws+/DRXTBaXo4RlQImHFiLIh7W6eacIzle",
	"0FmmvRz9Oba1AL5CrLiGtyN9qXKdY84a2gcQW7Nz0aK3fqJ2iUnbhfTKfhkyvYvnGFMN5SmpSCcP6cZX",
	"6xTfeoNpnMeQE7WIRpKS7q5hc/vvyVBOXxhFTziWi6UqAxnJRO8YONZQRC39pMVR9z2qmPq3+fhlo9OH",
	"OunxEetE7tNCVvV+RnTE9/afuW1Zcf7XYHoyUQ+yctbjQib6B7ZHz1KcBi1uM1N30JUwX76crEeDfmXM",
	"oUS06pc1EiCBLKdlAlAI2/06KJY5akXeuiGvYoDtZW5kQOQ5CJZzonOI+cZfhdl78+WeZx/kVpPv726u",
	"MPbzGPwFmp8Cur1ZkQ/+14gWCjOInTG5XsxmMgfhprOupNrO/Md6dnuzajSVaJMIjegDKNcVpddX86u5",
	"zQAcQLqgr+xPkR2GswpYDzs4vlIwFh5ak+UDqx361v6+tH6gdVH9cv460NYCY6+O3W72Ova1WxdS92q/",
	"WfvO9lhd+x0qBG6aAw+ebTUepTWo+2PUmlUcCBb1klk5PHi8t6KId32W/ewPbc5eHYZ5aIxnzTpjQ8ee",
	"zObjsujdBlshzp8sxAuIHtkZFHth+qILTX2cI8dT0yN/dqF63lCuf9GNSZG+kI9Rw0hnmXyA7mzuRfTd",
	"jzWdc06diag/+9EgO24iLCdSkUTuRTMlC59Q+dY1VaQOmEV7qOccQYeHPvvyvh4XQHjC6Eyht8TndrbD",
	"TgGRrSo5deQ2a414bCEgwGoQ5a5s1TzFBuqB7aG6tbO4Hp+e8EE9HT9hcWPYecLq/kAymvH5Jtaf57nE",
	"sa/6Iy9TTn1a5tEymrH0Y9UcX3uWHGREr6Ow+pZL3hxuEno5H/mNTP0IpjkNvT4QV74E+XqWLKuuc5qD",
	"2GdkXK3p8rOiUGio8T+ceAXm1INWZTsN6qE8ms4VgZIJWbP4C4iEuGW9amO/31/pPc9SudVXscxmWDHg",
	"0XlyVclSkz3eH/8dAAD//43eaaw0NAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
