openapi: 3.0.3
info:
  version: '1.0.0'
  title: SwimLogs API
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
    
  description: Openapi specification for SwimLogs API v1.

tags:
  - name: Session
  - name: Training

paths:
  /session:
    get:
      description: Return all sessions
      tags:
        - Session
      operationId: getAllSessions
      responses:
        200:
          $ref: '#/components/responses/GetAllSessionsResponse'

    post:
      description: Creates new session
      tags:
        - Session
      operationId: createSession
      requestBody:
        $ref: '#/components/requestBodies/CreateSessionRequest'
      responses:
          201:
            $ref: '#/components/responses/CreateSessionResponse'
  
  /session/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Id of a session
        schema:
          type: string
          format: uuid
    delete:
      description: Deletes a session with matching id
      tags:
        - Session
      operationId: deleteSession
      responses:
        200:
          description: Session deleted
    put:
      description: Updates session with specified id
      tags:
        - Session
      operationId: updateSession
      requestBody:
        $ref: '#/components/requestBodies/UpdateSessionRequest'
      responses:
        200:
          $ref: '#/components/responses/UpdateSessionResponse'
  
  /training:
    post:
      description: Creates new training
      tags:
        - Training
      operationId: createTraining
      requestBody:
        $ref: '#/components/requestBodies/CreateTrainingRequest'
      responses:
        201:
          $ref: '#/components/responses/CreateTrainingResponse'

  /training/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Id of a training
        schema:
          type: string
          format: uuid
    get:
      description: Get a training with matching id
      tags:
        - Training
      operationId: getTrainingById
      responses:
        200:
          $ref: '#/components/responses/GetTrainingResponse'
    put:
      description: Updates training with matching id according to the training
        object in the request. The Id of the object is ignored, as it can't be
        changed.
      tags:
        - Training
      operationId: updateTraining
      requestBody:
        $ref: '#/components/requestBodies/UpdateTrainingRequest'
      responses:
        200:
          $ref: '#/components/responses/UpdateTrainingResponse'
    delete:
      description: Deletes a training with matching id
      tags:
        - Training
      operationId: deleteTraining
      responses:
        200:
          description: Training was deleted


components:
  requestBodies:
    CreateSessionRequest:
      description: Request for creating new session. Id of the session
        is ignored, and new one is generated.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Session'
    
    UpdateSessionRequest:
      description: Request for updating an existing session according to sent
        Session object in this request. The Id of the object is ignored.
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Session"
    
    CreateTrainingRequest:
      description: Request for creating a training. Id on this object is ignored
        and new one is generated by the server.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Training'
      
    UpdateTrainingRequest:
      description: Request for updating an existing training according to this
        request. The Id field won't be updated.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Training'
  
  responses:
    GetAllSessionsResponse:
      description: Response containing all sessions
      content:
        application/json:
          schema:
            type: object
            properties:
              sessions:
                type: array
                items:
                  $ref: '#/components/schemas/Session'

    CreateSessionResponse:
      description: A new session was successfully created and
        it is returned, also with newly generated id.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Session'
    
    UpdateSessionResponse:
      description: Returns the updated Session
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Session'
    
    CreateTrainingResponse:
      description: New training was successfully created and it is returned,
        also with newly generated id.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Training'
    
    GetTrainingResponse:
      description: Response with a training 
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Training'

    UpdateTrainingResponse:
      description: Returns the updated Training
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Training'
    
  schemas:
    Session:
      type: object
      properties:
        id:
          type: string
          format: uuid
        day:
          type: string
          enum:
          - monday
          - tuesday
          - wednesday
          - thursday
          - friday
          - saturday
          - sunday
          description: On which day does the session occur
        startTime:
          type: string
          pattern: ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$
          description: When does the session start during the day
        durationMin:
          type: integer
          description: How long does the session last, in minutes
          example: 60
      required:
        - id
        - day
        - startTime
        - durationMin
      
    StartingRule:
      type: object
      properties:
        rule:
          type: string
          description: What instance of rule this is
          enum:
            - none
            - interval
            - pause
        seconds:
          type: integer
          description: Used by rules which require a time parameter
      required:
        - rule

    Set:
      type: object
      properties:
        repeat:
          type: integer
          description: How many times to repeat the distance
        distance:
          type: integer
        what:
          type: string
          description: Description of what to swim
        startingRule:
          $ref: '#/components/schemas/StartingRule'
      required:
        - repeat
        - distance
        - what
        - startingRule
    
    Block:
      type: object
      properties:
        repeat:
          type: integer
          description: How many times to repeat the block
        name:
          type: string
          example: Warm up
        sets:
          type: array
          items:
            $ref: '#/components/schemas/Set'
      required:
        - repeat
        - name
        - sets

    Training:
      type: object
      properties:
        id:
          type: string
          format: uuid
        date:
          type: string
          format: date
          description: On what date does the training occur.
        sessionId:
          type: string
          format: uuid
          description: A session from which to copy day, start time and
            duration to this training. 
        day:
          type: string
          enum:
          - monday
          - tuesday
          - wednesday
          - thursday
          - friday
          - saturday
          - sunday
          description: If sessionId isn't set, then this field is required!
            On which day does the training occur
        startTime:
          type: string
          pattern: ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$
          description: If sessionId isn't set, then this field is required!
            When does the training start during the day.
        durationMin:
          type: integer
          description: If sessionId isn't set, then this field is required!
            How long does the session last, in minutes
          example: 60
        blocks:
          type: array
          items:
            $ref: '#/components/schemas/Block'
      required:
        - date
        - blocks






