openapi: 3.0.3
info:
  version: '1.3.0'
  title: SwimLogs API
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
  description: Openapi specification for SwimLogs API.

tags:
  - name: Session
  - name: Training

paths:
  /sessions:
    get:
      description: Return all sessions
      tags:
        - Session
      operationId: getAllSessions
      responses:
        200:
          description: Response containing all sessions
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Session'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
    post:
      description: Creates new session
      tags:
        - Session
      operationId: createSession
      requestBody:
        $ref: '#/components/requestBodies/CreateSessionRequest'
      responses:
        201:
          description: A new session was successfully created and
            it is returned, also with newly generated id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        400:
          $ref: '#/components/responses/InvalidSessionErrorResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'

  /sessions/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Id of a session
        schema:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
    delete:
      description: Deletes a session with matching id
      tags:
        - Session
      operationId: deleteSession
      responses:
        200:
          description: Session deleted
        404:
          $ref: '#/components/responses/SessionNotFoundErrorResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
    put:
      description: Updates session with specified id
      tags:
        - Session
      operationId: updateSession
      requestBody:
        $ref: '#/components/requestBodies/UpdateSessionRequest'
      responses:
        200:
          description: Returns the updated Session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        400:
          $ref: '#/components/responses/InvalidSessionErrorResponse'
        404:
          $ref: '#/components/responses/SessionNotFoundErrorResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'

  /trainings:
    get:
      description: Returns paginated list of trainings
      tags:
        - Training
      operationId: getTrainings
      parameters:
        - name: page
          in: query
          required: true
          description: Which page to return, starts at 0
          schema:
            type: integer
            example: 0
        - name: pageSize
          in: query
          required: true
          description: How many trainings to return
          schema:
            type: integer
            example: 10
      responses:
        200:
          $ref: '#/components/responses/GetTrainingsResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
    post:
      description: Creates new training
      tags:
        - Training
      operationId: createTraining
      requestBody:
        $ref: '#/components/requestBodies/CreateTrainingRequest'
      responses:
        201:
          description: New training was successfully created and it is returned,
            also with newly generated id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
        400:
          $ref: '#/components/responses/InvalidTrainingErrorResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
  /trainings/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Id of a training
        schema:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
    get:
      description: Get a training with matching id
      tags:
        - Training
      operationId: getTrainingById
      responses:
        200:
          description: Response with a training
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
        404:
          $ref: '#/components/responses/TrainingNotFoundErrorResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
    put:
      description: Updates training with matching id according to the training
        object in the request. The Id of the object is ignored, as it can't be
        changed.
      tags:
        - Training
      operationId: updateTraining
      requestBody:
        $ref: '#/components/requestBodies/UpdateTrainingRequest'
      responses:
        200:
          description: Returns the updated Training
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
        400:
          $ref: '#/components/responses/InvalidTrainingErrorResponse'
        404:
          $ref: '#/components/responses/TrainingNotFoundErrorResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
    delete:
      description: Deletes a training with matching id
      tags:
        - Training
      operationId: deleteTraining
      responses:
        200:
          description: Training was deleted
        404:
          $ref: '#/components/responses/TrainingNotFoundErrorResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
  
  /trainings/details:
    get:
      description: Returns paginated list of details about trainings
      tags:
        - Training
      operationId: getTrainingsDetails
      parameters:
        - name: page
          in: query
          required: true
          description: Which page to return, starts at 0
          schema:
            type: integer
            example: 0
        - name: pageSize
          in: query
          required: true
          description: How many details to return
          schema:
            type: integer
            example: 10
      responses:
        200:
          $ref: '#/components/responses/GetTrainingDetailsResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'

components:
  requestBodies:
    CreateSessionRequest:
      description: Request for creating new session. Id of the session
        is ignored, and new one is generated.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Session'

    UpdateSessionRequest:
      description: Request for updating an existing session according to sent
        Session object in this request. The Id of the object is ignored.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Session'

    CreateTrainingRequest:
      description: Request for creating a training. Id on this object is ignored
        and new one is generated by the server.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Training'

    UpdateTrainingRequest:
      description: Request for updating an existing training according to this
        request. The Id field won't be updated.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Training'

  responses:
    GetTrainingsResponse:
      description: Paginated list of trainings
      content:
        application/json:
          schema:
            type: object
            properties:
              trainings:
                type: array
                items:
                  $ref: '#/components/schemas/Training'
              pagination:
                $ref: '#/components/schemas/Pagination'
    
    GetTrainingDetailsResponse:
      description: Paginated list of training details
      content:
        application/json:
          schema:
            type: object
            properties:
              details:
                type: array
                items:
                  $ref: '#/components/schemas/TrainingDetail'
              pagination:
                $ref: '#/components/schemas/Pagination'
    
    TrainingNotFoundErrorResponse:
      description: Training with specified id wasn't found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDetail'
          example:
            title: Training wasn't found
            detail: Training with Id 'XYZ' wasn't found.
      
    InvalidTrainingErrorResponse:
      description: Training wasn't valid. Contains additional properties
        indicating which fields were invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDetail'
          example:
            title: Invalid training
            detail: There were invalid training attributes
            sessionId: Unknown session Id 'XYZ'
            day: Unknown day name 'mondy'

    SessionNotFoundErrorResponse:
      description: Session with matching Id wasn't found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDetail'
          example:
            title: Session wasn't found
            details: Session with Id 'XYZ' wasn't found
    
    InvalidSessionErrorResponse:
      description: Request wasn't valid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDetail'
          example:
            title: Invalid request 
            details: There were invalid session attributes
            day: Unknown day name 'mondy'
            startTime: Start time must be from 00:00 to 23:59, but was '43:32'
            durationMin: Duration can't be 0
    
    InternalServerErrorResponse:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDetail'
          example:
            title: Internal server error
            details: Internal server error

  schemas:
    Day:
      type: string
      enum:
        - monday
        - tuesday
        - wednesday
        - thursday
        - friday
        - saturday
        - sunday

    Session:
      type: object
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
        day:
          $ref: '#/components/schemas/Day'
          description: On which day does the session occur
        startTime:
          type: string
          pattern: ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$
          description: When does the session start during the day
        durationMin:
          type: integer
          description: How long does the session last, in minutes
          example: 60
      required:
        - id
        - day
        - startTime
        - durationMin
      additionalProperties: false

    StartingRule:
      type: object
      properties:
        rule:
          type: string
          description: What instance of rule this is
          enum:
            - none
            - interval
            - pause
          example: interval
        seconds:
          type: integer
          description: Used by rules which require a time parameter
          example: 60
      required:
        - rule
      additionalProperties: false

    Set:
      type: object
      properties:
        repeat:
          type: integer
          description: How many times to repeat the distance
          minimum: 1
        distance:
          type: integer
          example: 400
        what:
          type: string
          description: Description of what to swim
          example: Freestyle
        startingRule:
          $ref: '#/components/schemas/StartingRule'
      required:
        - repeat
        - distance
        - what
        - startingRule
      additionalProperties: false

    Block:
      type: object
      properties:
        repeat:
          type: integer
          description: How many times to repeat the block
          minimum: 1
        name:
          type: string
          example: Warm up
          maxLength: 255
        sets:
          type: array
          items:
            $ref: '#/components/schemas/Set'
      required:
        - repeat
        - name
        - sets
      additionalProperties: false

    Training:
      type: object
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
        date:
          type: string
          format: date
          description: On what date does the training occur.
        sessionId:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
          description: A session from which to copy day, start time and
            duration to this training.
        day:
          $ref: '#/components/schemas/Day'
          description: If sessionId isn't set, then this field is required!
            On which day does the training occur
        startTime:
          type: string
          pattern: ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$
          description: If sessionId isn't set, then this field is required!
            When does the training start during the day.
        durationMin:
          type: integer
          description: If sessionId isn't set, then this field is required!
            How long does the session last, in minutes
          example: 60
        blocks:
          type: array
          items:
            $ref: '#/components/schemas/Block'
      required:
        - id
        - date
        - blocks
      additionalProperties: false

    TrainingDetail:
      type: object
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
        date:
          type: string
          format: date
          description: On what date does the training occur.
        day:
          $ref: '#/components/schemas/Day'
          description: If sessionId isn't set, then this field is required!
            On which day does the training occur
        startTime:
          type: string
          pattern: ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$
          description: If sessionId isn't set, then this field is required!
            When does the training start during the day.
        durationMin:
          type: integer
          description: If sessionId isn't set, then this field is required!
            How long does the session last, in minutes
          example: 60
        totalDist:
          type: integer
          description: Total distance in the training in meters
          example: 2200
      required:
        - id
        - date
        - day
        - startTime
        - durationMin
        - totalDist
      additionalProperties: false
    
    Pagination:
      description: Pagination metadata about paginated response
      type: object
      properties:
        total:
          type: integer
          description: Total count of all items
          example: 13
        page:
          type: integer
          description: Number of page returned
          example: 0
        pageSize:
          type: integer
          description: How many items are in page
          example: 10
      additionalProperties: false
  
    ErrorDetail:
      type: object
      properties:
        title:
          type: string
          description: Short human-readable summary of the error
          example: "Session not found"
        detail:
          type: string
          description: A human-readable explanation of the error
          example: "Session with Id XYZ wasn't found."
      required:
        - title
        - detail
      additionalProperties:
        type: string
        description: Extensions of the standard ErrorDetail format, if needed


