// Package oapiGen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package oapiGen

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/google/uuid"
)

// Defines values for Day.
const (
	Friday    Day = "friday"
	Monday    Day = "monday"
	Saturday  Day = "saturday"
	Sunday    Day = "sunday"
	Thursday  Day = "thursday"
	Tuesday   Day = "tuesday"
	Wednesday Day = "wednesday"
)

// Defines values for StartingRuleRule.
const (
	Interval StartingRuleRule = "interval"
	None     StartingRuleRule = "none"
	Pause    StartingRuleRule = "pause"
)

// Block defines model for Block.
type Block struct {
	Id   uuid.UUID `json:"id"`
	Name string    `json:"name"`

	// Num Number of the block, indicates in what order the blocks in training are supposed to be.
	Num int `json:"num"`

	// Repeat How many times to repeat the block
	Repeat int   `json:"repeat"`
	Sets   []Set `json:"sets"`

	// TotalDist Total distance in this block. Computed on server, ignored on incoming requests.
	TotalDist *int `json:"totalDist,omitempty"`
}

// Day defines model for Day.
type Day string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Detail A human-readable explanation of the error
	Detail string `json:"detail"`

	// Title Short human-readable summary of the error
	Title string `json:"title"`
}

// ErrorLog defines model for ErrorLog.
type ErrorLog struct {
	// ErrMsg Error message of what went wrong
	ErrMsg string `json:"errMsg"`

	// UserDesc Optional description from user
	UserDesc *string `json:"userDesc,omitempty"`
}

// InvalidBlock defines model for InvalidBlock.
type InvalidBlock struct {
	Name *string `json:"name,omitempty"`

	// Num The number of invalid block in training
	Num    *int          `json:"num,omitempty"`
	Repeat *string       `json:"repeat,omitempty"`
	Sets   *[]InvalidSet `json:"sets,omitempty"`
}

// InvalidSession defines model for InvalidSession.
type InvalidSession struct {
	Day         *string `json:"day,omitempty"`
	DurationMin *string `json:"durationMin,omitempty"`
	StartTime   *string `json:"startTime,omitempty"`
}

// InvalidSet defines model for InvalidSet.
type InvalidSet struct {
	Distance *string `json:"distance,omitempty"`

	// Num The number of invalid set in training
	Num          *int    `json:"num,omitempty"`
	Repeat       *string `json:"repeat,omitempty"`
	StartingRule *struct {
		Rule    *string `json:"rule,omitempty"`
		Seconds *string `json:"seconds,omitempty"`
	} `json:"startingRule,omitempty"`
}

// InvalidTraining defines model for InvalidTraining.
type InvalidTraining struct {
	Blocks      *[]InvalidBlock `json:"blocks,omitempty"`
	Date        *string         `json:"date,omitempty"`
	Day         *string         `json:"day,omitempty"`
	DurationMin *string         `json:"durationMin,omitempty"`
	StartTime   *string         `json:"startTime,omitempty"`
}

// Pagination Pagination metadata about paginated response
type Pagination struct {
	// Page Number of page returned
	Page int `json:"page"`

	// PageSize How many items are in page
	PageSize int `json:"pageSize"`

	// Total Total count of all items
	Total int `json:"total"`
}

// Session defines model for Session.
type Session struct {
	Day Day `json:"day"`

	// DurationMin How long does the session last, in minutes
	DurationMin int       `json:"durationMin"`
	Id          uuid.UUID `json:"id"`

	// StartTime When does the session start during the day
	StartTime string `json:"startTime"`

	// Version Version of this session, used for optimistic locking
	Version int `json:"version"`
}

// Set defines model for Set.
type Set struct {
	Distance int       `json:"distance"`
	Id       uuid.UUID `json:"id"`

	// Num Number of the set, indicates in what order the sets in block are supposed to be.
	Num int `json:"num"`

	// Repeat How many times to repeat the distance
	Repeat       int          `json:"repeat"`
	StartingRule StartingRule `json:"startingRule"`

	// TotalDist Total distance in this set. Computed on server, ignored on incoming requests.
	TotalDist *int `json:"totalDist,omitempty"`

	// What Description of what to swim
	What string `json:"what"`
}

// StartingRule defines model for StartingRule.
type StartingRule struct {
	// Rule What instance of rule this is
	Rule StartingRuleRule `json:"rule"`

	// Seconds Used by rules which require a time parameter
	Seconds *int `json:"seconds,omitempty"`
}

// StartingRuleRule What instance of rule this is
type StartingRuleRule string

// Training defines model for Training.
type Training struct {
	Blocks []Block `json:"blocks"`

	// Date On what date does the training occur.
	Date openapi_types.Date `json:"date"`
	Day  *Day               `json:"day,omitempty"`

	// DurationMin If sessionId isn't set, then this field is required! How long does the session last, in minutes
	DurationMin *int      `json:"durationMin,omitempty"`
	Id          uuid.UUID `json:"id"`

	// SessionId A session from which to copy day, start time and duration to this training.
	SessionId *uuid.UUID `json:"sessionId,omitempty"`

	// StartTime If sessionId isn't set, then this field is required! When does the training start during the day.
	StartTime *string `json:"startTime,omitempty"`

	// TotalDist Total distance in this training. Computed on server, ignored on incoming requests.
	TotalDist *int `json:"totalDist,omitempty"`

	// Version Version of this training, used for optimistic locking
	Version int `json:"version"`
}

// TrainingDetail defines model for TrainingDetail.
type TrainingDetail struct {
	// Date On what date does the training occur.
	Date openapi_types.Date `json:"date"`
	Day  Day                `json:"day"`

	// DurationMin If sessionId isn't set, then this field is required! How long does the session last, in minutes
	DurationMin int       `json:"durationMin"`
	Id          uuid.UUID `json:"id"`

	// StartTime If sessionId isn't set, then this field is required! When does the training start during the day.
	StartTime string `json:"startTime"`

	// TotalDist Total distance in the training in meters
	TotalDist int `json:"totalDist"`
}

// GetTrainingsResponse defines model for GetTrainingsResponse.
type GetTrainingsResponse struct {
	// Pagination Pagination metadata about paginated response
	Pagination *Pagination `json:"pagination,omitempty"`
	Trainings  *[]Training `json:"trainings,omitempty"`
}

// InvalidSessionErrorResponse defines model for InvalidSessionErrorResponse.
type InvalidSessionErrorResponse = InvalidSession

// InvalidTrainingErrorResponse defines model for InvalidTrainingErrorResponse.
type InvalidTrainingErrorResponse = InvalidTraining

// SessionNotFoundErrorResponse defines model for SessionNotFoundErrorResponse.
type SessionNotFoundErrorResponse = ErrorDetail

// TrainingNotFoundErrorResponse defines model for TrainingNotFoundErrorResponse.
type TrainingNotFoundErrorResponse = ErrorDetail

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest = Session

// CreateTrainingRequest defines model for CreateTrainingRequest.
type CreateTrainingRequest = Training

// ErrorLogRequest defines model for ErrorLogRequest.
type ErrorLogRequest = ErrorLog

// UpdateSessionRequest defines model for UpdateSessionRequest.
type UpdateSessionRequest = Session

// UpdateTrainingRequest defines model for UpdateTrainingRequest.
type UpdateTrainingRequest = Training

// GetTrainingsParams defines parameters for GetTrainings.
type GetTrainingsParams struct {
	// Page Which page to return, starts at 0
	Page int `form:"page" json:"page"`

	// PageSize How many trainings to return
	PageSize int `form:"pageSize" json:"pageSize"`
}

// GetTrainingsDetailsParams defines parameters for GetTrainingsDetails.
type GetTrainingsDetailsParams struct {
	// Page Which page to return, starts at 0
	Page int `form:"page" json:"page"`

	// PageSize How many details to return
	PageSize int `form:"pageSize" json:"pageSize"`
}

// RecordErrorJSONRequestBody defines body for RecordError for application/json ContentType.
type RecordErrorJSONRequestBody = ErrorLog

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = Session

// UpdateSessionJSONRequestBody defines body for UpdateSession for application/json ContentType.
type UpdateSessionJSONRequestBody = Session

// CreateTrainingJSONRequestBody defines body for CreateTraining for application/json ContentType.
type CreateTrainingJSONRequestBody = Training

// UpdateTrainingJSONRequestBody defines body for UpdateTraining for application/json ContentType.
type UpdateTrainingJSONRequestBody = Training
