// Package oapiGen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package oapiGen
//lint:file-ignore ST1005 generated code

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /logs)
	RecordError(ctx echo.Context) error

	// (GET /sessions)
	GetAllSessions(ctx echo.Context) error

	// (POST /sessions)
	CreateSession(ctx echo.Context) error

	// (DELETE /sessions/{id})
	DeleteSession(ctx echo.Context, id uuid.UUID) error

	// (PUT /sessions/{id})
	UpdateSession(ctx echo.Context, id uuid.UUID) error

	// (GET /trainings)
	GetTrainings(ctx echo.Context, params GetTrainingsParams) error

	// (POST /trainings)
	CreateTraining(ctx echo.Context) error

	// (GET /trainings/details)
	GetTrainingsDetails(ctx echo.Context, params GetTrainingsDetailsParams) error

	// (GET /trainings/details/current-week)
	GetTrainingsDetailsCurrentWeek(ctx echo.Context) error

	// (DELETE /trainings/{id})
	DeleteTraining(ctx echo.Context, id uuid.UUID) error

	// (GET /trainings/{id})
	GetTrainingById(ctx echo.Context, id uuid.UUID) error

	// (PUT /trainings/{id})
	UpdateTraining(ctx echo.Context, id uuid.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// RecordError converts echo context to params.
func (w *ServerInterfaceWrapper) RecordError(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RecordError(ctx)
	return err
}

// GetAllSessions converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllSessions(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetAllSessions(ctx)
	return err
}

// CreateSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSession(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateSession(ctx)
	return err
}

// DeleteSession converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSession(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id uuid.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteSession(ctx, id)
	return err
}

// UpdateSession converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateSession(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id uuid.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateSession(ctx, id)
	return err
}

// GetTrainings converts echo context to params.
func (w *ServerInterfaceWrapper) GetTrainings(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTrainingsParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, true, "pageSize", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageSize: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetTrainings(ctx, params)
	return err
}

// CreateTraining converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTraining(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateTraining(ctx)
	return err
}

// GetTrainingsDetails converts echo context to params.
func (w *ServerInterfaceWrapper) GetTrainingsDetails(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTrainingsDetailsParams
	// ------------- Required query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, true, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Required query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, true, "pageSize", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageSize: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetTrainingsDetails(ctx, params)
	return err
}

// GetTrainingsDetailsCurrentWeek converts echo context to params.
func (w *ServerInterfaceWrapper) GetTrainingsDetailsCurrentWeek(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetTrainingsDetailsCurrentWeek(ctx)
	return err
}

// DeleteTraining converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTraining(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id uuid.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteTraining(ctx, id)
	return err
}

// GetTrainingById converts echo context to params.
func (w *ServerInterfaceWrapper) GetTrainingById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id uuid.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetTrainingById(ctx, id)
	return err
}

// UpdateTraining converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTraining(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id uuid.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateTraining(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/logs", wrapper.RecordError)
	router.GET(baseURL+"/sessions", wrapper.GetAllSessions)
	router.POST(baseURL+"/sessions", wrapper.CreateSession)
	router.DELETE(baseURL+"/sessions/:id", wrapper.DeleteSession)
	router.PUT(baseURL+"/sessions/:id", wrapper.UpdateSession)
	router.GET(baseURL+"/trainings", wrapper.GetTrainings)
	router.POST(baseURL+"/trainings", wrapper.CreateTraining)
	router.GET(baseURL+"/trainings/details", wrapper.GetTrainingsDetails)
	router.GET(baseURL+"/trainings/details/current-week", wrapper.GetTrainingsDetailsCurrentWeek)
	router.DELETE(baseURL+"/trainings/:id", wrapper.DeleteTraining)
	router.GET(baseURL+"/trainings/:id", wrapper.GetTrainingById)
	router.PUT(baseURL+"/trainings/:id", wrapper.UpdateTraining)

}

type EditConflictResponseResponse struct {
}

type GetTrainingsResponseJSONResponse struct {
	// Pagination Pagination metadata about paginated response
	Pagination *Pagination `json:"pagination,omitempty"`
	Trainings  *[]Training `json:"trainings,omitempty"`
}

type InvalidSessionErrorResponseJSONResponse InvalidSession

type InvalidTrainingErrorResponseJSONResponse InvalidTraining

type SessionNotFoundErrorResponseJSONResponse ErrorDetail

type TrainingNotFoundErrorResponseJSONResponse ErrorDetail

type RecordErrorRequestObject struct {
	Body *RecordErrorJSONRequestBody
}

type RecordErrorResponseObject interface {
	VisitRecordErrorResponse(w http.ResponseWriter) error
}

type RecordError200Response struct {
}

func (response RecordError200Response) VisitRecordErrorResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetAllSessionsRequestObject struct {
}

type GetAllSessionsResponseObject interface {
	VisitGetAllSessionsResponse(w http.ResponseWriter) error
}

type GetAllSessions200JSONResponse struct {
	Sessions []Session `json:"sessions"`
}

func (response GetAllSessions200JSONResponse) VisitGetAllSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllSessions500Response struct {
}

func (response GetAllSessions500Response) VisitGetAllSessionsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession201JSONResponse Session

func (response CreateSession201JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession400JSONResponse struct {
	InvalidSessionErrorResponseJSONResponse
}

func (response CreateSession400JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession500Response struct {
}

func (response CreateSession500Response) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type DeleteSessionRequestObject struct {
	Id uuid.UUID `json:"id"`
}

type DeleteSessionResponseObject interface {
	VisitDeleteSessionResponse(w http.ResponseWriter) error
}

type DeleteSession200Response struct {
}

func (response DeleteSession200Response) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteSession404JSONResponse struct {
	SessionNotFoundErrorResponseJSONResponse
}

func (response DeleteSession404JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSession500Response struct {
}

func (response DeleteSession500Response) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type UpdateSessionRequestObject struct {
	Id   uuid.UUID `json:"id"`
	Body *UpdateSessionJSONRequestBody
}

type UpdateSessionResponseObject interface {
	VisitUpdateSessionResponse(w http.ResponseWriter) error
}

type UpdateSession200JSONResponse Session

func (response UpdateSession200JSONResponse) VisitUpdateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSession400JSONResponse struct {
	InvalidSessionErrorResponseJSONResponse
}

func (response UpdateSession400JSONResponse) VisitUpdateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSession404JSONResponse struct {
	SessionNotFoundErrorResponseJSONResponse
}

func (response UpdateSession404JSONResponse) VisitUpdateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSession409Response = EditConflictResponseResponse

func (response UpdateSession409Response) VisitUpdateSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type UpdateSession500Response struct {
}

func (response UpdateSession500Response) VisitUpdateSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetTrainingsRequestObject struct {
	Params GetTrainingsParams
}

type GetTrainingsResponseObject interface {
	VisitGetTrainingsResponse(w http.ResponseWriter) error
}

type GetTrainings200JSONResponse struct {
	GetTrainingsResponseJSONResponse
}

func (response GetTrainings200JSONResponse) VisitGetTrainingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTrainings500Response struct {
}

func (response GetTrainings500Response) VisitGetTrainingsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type CreateTrainingRequestObject struct {
	Body *CreateTrainingJSONRequestBody
}

type CreateTrainingResponseObject interface {
	VisitCreateTrainingResponse(w http.ResponseWriter) error
}

type CreateTraining201JSONResponse TrainingDetail

func (response CreateTraining201JSONResponse) VisitCreateTrainingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTraining400JSONResponse struct {
	InvalidTrainingErrorResponseJSONResponse
}

func (response CreateTraining400JSONResponse) VisitCreateTrainingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTraining500Response struct {
}

func (response CreateTraining500Response) VisitCreateTrainingResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetTrainingsDetailsRequestObject struct {
	Params GetTrainingsDetailsParams
}

type GetTrainingsDetailsResponseObject interface {
	VisitGetTrainingsDetailsResponse(w http.ResponseWriter) error
}

type GetTrainingsDetails200JSONResponse struct {
	Details []TrainingDetail `json:"details"`

	// Pagination Pagination metadata about paginated response
	Pagination Pagination `json:"pagination"`
}

func (response GetTrainingsDetails200JSONResponse) VisitGetTrainingsDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTrainingsDetails400JSONResponse ErrorDetail

func (response GetTrainingsDetails400JSONResponse) VisitGetTrainingsDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTrainingsDetails500Response struct {
}

func (response GetTrainingsDetails500Response) VisitGetTrainingsDetailsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetTrainingsDetailsCurrentWeekRequestObject struct {
}

type GetTrainingsDetailsCurrentWeekResponseObject interface {
	VisitGetTrainingsDetailsCurrentWeekResponse(w http.ResponseWriter) error
}

type GetTrainingsDetailsCurrentWeek200JSONResponse struct {
	Details *[]TrainingDetail `json:"details,omitempty"`
}

func (response GetTrainingsDetailsCurrentWeek200JSONResponse) VisitGetTrainingsDetailsCurrentWeekResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTrainingsDetailsCurrentWeek500Response struct {
}

func (response GetTrainingsDetailsCurrentWeek500Response) VisitGetTrainingsDetailsCurrentWeekResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type DeleteTrainingRequestObject struct {
	Id uuid.UUID `json:"id"`
}

type DeleteTrainingResponseObject interface {
	VisitDeleteTrainingResponse(w http.ResponseWriter) error
}

type DeleteTraining200Response struct {
}

func (response DeleteTraining200Response) VisitDeleteTrainingResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteTraining404JSONResponse struct {
	TrainingNotFoundErrorResponseJSONResponse
}

func (response DeleteTraining404JSONResponse) VisitDeleteTrainingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTraining500Response struct {
}

func (response DeleteTraining500Response) VisitDeleteTrainingResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetTrainingByIdRequestObject struct {
	Id uuid.UUID `json:"id"`
}

type GetTrainingByIdResponseObject interface {
	VisitGetTrainingByIdResponse(w http.ResponseWriter) error
}

type GetTrainingById200JSONResponse Training

func (response GetTrainingById200JSONResponse) VisitGetTrainingByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTrainingById404JSONResponse struct {
	TrainingNotFoundErrorResponseJSONResponse
}

func (response GetTrainingById404JSONResponse) VisitGetTrainingByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTrainingById500Response struct {
}

func (response GetTrainingById500Response) VisitGetTrainingByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type UpdateTrainingRequestObject struct {
	Id   uuid.UUID `json:"id"`
	Body *UpdateTrainingJSONRequestBody
}

type UpdateTrainingResponseObject interface {
	VisitUpdateTrainingResponse(w http.ResponseWriter) error
}

type UpdateTraining200JSONResponse TrainingDetail

func (response UpdateTraining200JSONResponse) VisitUpdateTrainingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTraining400JSONResponse struct {
	InvalidTrainingErrorResponseJSONResponse
}

func (response UpdateTraining400JSONResponse) VisitUpdateTrainingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTraining404JSONResponse struct {
	TrainingNotFoundErrorResponseJSONResponse
}

func (response UpdateTraining404JSONResponse) VisitUpdateTrainingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTraining409Response = EditConflictResponseResponse

func (response UpdateTraining409Response) VisitUpdateTrainingResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type UpdateTraining500Response struct {
}

func (response UpdateTraining500Response) VisitUpdateTrainingResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /logs)
	RecordError(ctx context.Context, request RecordErrorRequestObject) (RecordErrorResponseObject, error)

	// (GET /sessions)
	GetAllSessions(ctx context.Context, request GetAllSessionsRequestObject) (GetAllSessionsResponseObject, error)

	// (POST /sessions)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)

	// (DELETE /sessions/{id})
	DeleteSession(ctx context.Context, request DeleteSessionRequestObject) (DeleteSessionResponseObject, error)

	// (PUT /sessions/{id})
	UpdateSession(ctx context.Context, request UpdateSessionRequestObject) (UpdateSessionResponseObject, error)

	// (GET /trainings)
	GetTrainings(ctx context.Context, request GetTrainingsRequestObject) (GetTrainingsResponseObject, error)

	// (POST /trainings)
	CreateTraining(ctx context.Context, request CreateTrainingRequestObject) (CreateTrainingResponseObject, error)

	// (GET /trainings/details)
	GetTrainingsDetails(ctx context.Context, request GetTrainingsDetailsRequestObject) (GetTrainingsDetailsResponseObject, error)

	// (GET /trainings/details/current-week)
	GetTrainingsDetailsCurrentWeek(ctx context.Context, request GetTrainingsDetailsCurrentWeekRequestObject) (GetTrainingsDetailsCurrentWeekResponseObject, error)

	// (DELETE /trainings/{id})
	DeleteTraining(ctx context.Context, request DeleteTrainingRequestObject) (DeleteTrainingResponseObject, error)

	// (GET /trainings/{id})
	GetTrainingById(ctx context.Context, request GetTrainingByIdRequestObject) (GetTrainingByIdResponseObject, error)

	// (PUT /trainings/{id})
	UpdateTraining(ctx context.Context, request UpdateTrainingRequestObject) (UpdateTrainingResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// RecordError operation middleware
func (sh *strictHandler) RecordError(ctx echo.Context) error {
	var request RecordErrorRequestObject

	var body RecordErrorJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RecordError(ctx.Request().Context(), request.(RecordErrorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RecordError")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RecordErrorResponseObject); ok {
		return validResponse.VisitRecordErrorResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetAllSessions operation middleware
func (sh *strictHandler) GetAllSessions(ctx echo.Context) error {
	var request GetAllSessionsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllSessions(ctx.Request().Context(), request.(GetAllSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllSessions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAllSessionsResponseObject); ok {
		return validResponse.VisitGetAllSessionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(ctx echo.Context) error {
	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx.Request().Context(), request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		return validResponse.VisitCreateSessionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// DeleteSession operation middleware
func (sh *strictHandler) DeleteSession(ctx echo.Context, id uuid.UUID) error {
	var request DeleteSessionRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSession(ctx.Request().Context(), request.(DeleteSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteSessionResponseObject); ok {
		return validResponse.VisitDeleteSessionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// UpdateSession operation middleware
func (sh *strictHandler) UpdateSession(ctx echo.Context, id uuid.UUID) error {
	var request UpdateSessionRequestObject

	request.Id = id

	var body UpdateSessionJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSession(ctx.Request().Context(), request.(UpdateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateSessionResponseObject); ok {
		return validResponse.VisitUpdateSessionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetTrainings operation middleware
func (sh *strictHandler) GetTrainings(ctx echo.Context, params GetTrainingsParams) error {
	var request GetTrainingsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTrainings(ctx.Request().Context(), request.(GetTrainingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTrainings")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTrainingsResponseObject); ok {
		return validResponse.VisitGetTrainingsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// CreateTraining operation middleware
func (sh *strictHandler) CreateTraining(ctx echo.Context) error {
	var request CreateTrainingRequestObject

	var body CreateTrainingJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTraining(ctx.Request().Context(), request.(CreateTrainingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTraining")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateTrainingResponseObject); ok {
		return validResponse.VisitCreateTrainingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetTrainingsDetails operation middleware
func (sh *strictHandler) GetTrainingsDetails(ctx echo.Context, params GetTrainingsDetailsParams) error {
	var request GetTrainingsDetailsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTrainingsDetails(ctx.Request().Context(), request.(GetTrainingsDetailsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTrainingsDetails")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTrainingsDetailsResponseObject); ok {
		return validResponse.VisitGetTrainingsDetailsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetTrainingsDetailsCurrentWeek operation middleware
func (sh *strictHandler) GetTrainingsDetailsCurrentWeek(ctx echo.Context) error {
	var request GetTrainingsDetailsCurrentWeekRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTrainingsDetailsCurrentWeek(ctx.Request().Context(), request.(GetTrainingsDetailsCurrentWeekRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTrainingsDetailsCurrentWeek")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTrainingsDetailsCurrentWeekResponseObject); ok {
		return validResponse.VisitGetTrainingsDetailsCurrentWeekResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// DeleteTraining operation middleware
func (sh *strictHandler) DeleteTraining(ctx echo.Context, id uuid.UUID) error {
	var request DeleteTrainingRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTraining(ctx.Request().Context(), request.(DeleteTrainingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTraining")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteTrainingResponseObject); ok {
		return validResponse.VisitDeleteTrainingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetTrainingById operation middleware
func (sh *strictHandler) GetTrainingById(ctx echo.Context, id uuid.UUID) error {
	var request GetTrainingByIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTrainingById(ctx.Request().Context(), request.(GetTrainingByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTrainingById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTrainingByIdResponseObject); ok {
		return validResponse.VisitGetTrainingByIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// UpdateTraining operation middleware
func (sh *strictHandler) UpdateTraining(ctx echo.Context, id uuid.UUID) error {
	var request UpdateTrainingRequestObject

	request.Id = id

	var body UpdateTrainingJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTraining(ctx.Request().Context(), request.(UpdateTrainingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTraining")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateTrainingResponseObject); ok {
		return validResponse.VisitUpdateTrainingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}
