description: List of training summaries in current week, sorted by date and start time
content:
  application/json:
    schema:
      type: object
      required:
        - summaries
      properties:
        summaries:
          type: array
          items:
            $ref: "../schemas/TrainingSummary.yaml"
