description: Response with a training
content:
  application/json:
    schema:
      $ref: "../schemas/Training.yaml"
      required:
        - id
        - start
        - durationMin
        - totalDistance
        - sets
