description: Paginated list of training summaries
content:
  application/json:
    schema:
      type: object
      properties:
        details:
          type: array
          items:
            $ref: "../schemas/TrainingSummary.yaml"
            required:
              - id
              - start
              - durationMin
              - totalDistance
        pagination:
          $ref: "../schemas/Pagination.yaml"
      required:
        - details
        - pagination
