description: Paginated list of training summaries
content:
  application/json:
    schema:
      type: object
      properties:
        summaries:
          type: array
          items:
            $ref: "../schemas/TrainingSummary.yaml"
        pagination:
          $ref: "../schemas/Pagination.yaml"
      required:
        - summaries
        - pagination
