openapi: 3.1.0
info:
  version: "1.0.0"
  title: SwimLogs API
  license:
    name: MIT License
    url: "https://opensource.org/licenses/MIT"
  description: Openapi specification for SwimLogs API.

servers:
  - url: https://www.swimlogs.com/api
    description: Prod backend server

tags:
  - name: Trainings

paths:
  /trainings:
    $ref: "./paths/trainings.yaml"
  /trainings/{id}:
    $ref: "./paths/trainings_{id}.yaml"
  /trainings/{id}/sets/{setId}:
    $ref: "./paths/trainings_{id}_sets_{setId}.yaml"
  /trainings/summaries:
    $ref: "./paths/trainings_summaries.yaml"
  /trainings/summaries/current-week:
    $ref: "./paths/trainings_summaries_current-week.yaml"
