name: Backend Docker Build & Push
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: nesquiko/swimlogs-backend
          tags: |
            type=semver,pattern={{version}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}
      # - uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}
      # - uses: docker/build-push-action@v4
      #   with:
      #     context: ./backend
      #     tags: ${{ steps.metadata.outputs.tags }}
      #     push: ${{ github.ref_type == 'tag' }}
      - run: sed -E 's|(nesquiko/swimlogs-backend:)[0-9]+\.[0-9]+\.[0-9]+|\1${{ steps.metadata.outputs.tags }}|' docker-compose.prod.yaml
