name: Backend Test, Build, Deploy
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_USER: swimlogs_test_user
          POSTGRES_PASSWORD: swimlogs_test_pass
          POSTGRES_DB: swimlogs_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    env:
      TEST_DB_HOST: localhost
      TEST_DB_PORT: 5432
      TEST_DB_USER: swimlogs_test_user
      TEST_DB_PASSWORD: swimlogs_test_pass
      TEST_DB_NAME: swimlogs_test_db
      INTEGRATION: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false # since it will be rebuilt in docker
      - run: go get .
      - run: go test -p 1 -count=1 -v ./...

  build:
    if: github.ref_type == 'tag'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: nesquiko/swimlogs-backend
          tags: type=semver,pattern={{version}}
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./backend
          tags: ${{ steps.metadata.outputs.tags }}
          push: ${{ github.ref_type == 'tag' }}

  deploy:
    if: github.ref_type == 'tag'
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sed -E 's|(nesquiko/swimlogs-backend:)[0-9]+\.[0-9]+\.[0-9]+|\1${{ steps.metadata.outputs.tags }}|' docker-compose.prod.yaml
