name: Backend Test, Build, Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - 'backend/**/*.go'
      - '.github/workflows/backend-docker.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**/*.go'
      - '.github/workflows/backend-docker.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./backend
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_USER: swimlogs_test_user
          POSTGRES_PASSWORD: swimlogs_test_pass
          POSTGRES_DB: swimlogs_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    env:
      TEST_DB_HOST: localhost
      TEST_DB_PORT: 5432
      TEST_DB_USER: swimlogs_test_user
      TEST_DB_PASSWORD: swimlogs_test_pass
      TEST_DB_NAME: swimlogs_test_db
      INTEGRATION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false # since it will be rebuilt in docker
      - name: Dowloand dependencies
        run: go get .
      - name: Dowloand Oapi-Codegen
        run: go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.13.0
      - name: Generate from OpenApi spec
        run: make generate
      - name: Test
        run: go test -p 1 -count=1 -v ./...

  build-push-docker:
    if: github.ref_type == 'tag'
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract tags for Docker
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: nesquiko/swimlogs-backend
          tags: type=semver,pattern={{version}}
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build & Push image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          tags: ${{ steps.metadata.outputs.tags }}
          push: ${{ github.ref_type == 'tag' }}

  deploy:
    if: github.ref_type == 'tag'
    needs: build-push-docker
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract latest version
        id: extract_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Update docker-compose.yaml
        run: sed -i -E 's|(nesquiko/swimlogs-backend:)latest|\1${{ steps.extract_version.outputs.version }}|' docker-compose.yaml
      - name: Deploy new docker-compose.yaml
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: 'docker-compose.yaml'
          target: /opt/swimlogs
      - name: Restart Docker compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /opt/swimlogs
            docker-compose up -d backend
