name: Backend Testcontainer test

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Dowloand Oapi-Codegen
        run: go install github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@ee101e4
      - name: Generate from OpenApi spec
        run: npm run --prefix ./api generate-go -y
      - name: Test
        working-directory: ./backend-rewrite
        run: go test -v ./...
